### ISSUE TITLE
page titles, subtitles, banner, overview page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#10]
In the EOWG telecon on 29 May, I thought Shadi said in IRC that these "quick start tips" were to help people *get started with accessibility*, and I thought Eric mentioned that "quick start" is redundant with tips -- but I don't see their comments in a skim of the minutes, so maybe they were in unlogged comments. Howard mentioned the idea of a banner, which I supported exploring.

Based on these ideas, I played with wording and design of the titles, subtitles and banner -- and mocked up <http://www.w3.org/WAI/EO/Drafts/qst-1slh.html> and <http://www.w3.org/WAI/EO/Drafts/qst-manage> (and also <http://www.w3.org/WAI/EO/Drafts/qst-manage2>. They're very rough, just to try to communicate the general ideas that I had in my head.

**Comment by slhenry** [comment]
Note that I had also considered Howard's suggestion of including some examples. I tried that but it didn't seem to work well. (I'm happy to explain if anyone wants to know.)

**Comment by iadawn** [comment]
I would like an explanation when you have a mo :)

**Comment by sharronrush** [comment]
I like this very much!

On Tue, Jun 2, 2015 at 4:05 PM, shawn_slh <notifications@github.com> wrote:

> In the EOWG telecon on 29 May, I thought Shadi said in IRC that these
> "quick start tips" were to help people *get started with accessibility*,
> and I thought Eric mentioned that "quick start" is redundant with tips --
> but I don't see their comments in a skim of the minutes, so maybe they were
> in unlogged comments. Howard mentioned the idea of a banner, which I
> supported exploring.
>
> Based on these ideas, I played with wording and design of the titles,
> subtitles and banner -- and mocked up
> http://www.w3.org/WAI/EO/Drafts/qst-1slh.html and
> http://www.w3.org/WAI/EO/Drafts/qst-manage (and also
> http://www.w3.org/WAI/EO/Drafts/qst-manage2. They're very rough, just to
> try to communicate the general ideas that I had in my head.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/wai-quick-start/issues/10>.
>



-- 
Sharron Rush | Executive Director | Knowbility.org | @knowbility
*Equal access to technology for people with disabilities*

**Comment by iadawn** [comment]
Mock-ups were discussed in [5th Jun EO Meeting](http://www.w3.org/2015/06/05-eo-minutes.html).

Main heading and introduction will be explored further in #14 and #15.
