### ISSUE TITLE
writing style

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#101]
1. WAI style is comma before conjunction, e.g.: apples, oranges, and bananas. <https://www.w3.org/WAI/EO/wiki/Style#Punctuation>

2. In the Tips for Designing, I *really* missed "that" in a few places, e.g.,:
- Ensure interactive elements are easy to identify
missing
- Ensure that interactive elements are easy to identify
and
- Ensure form elements include clearly associated labels
missing
- Ensure that form elements include clearly associated labels

I think either way is technically grammatically correct. (I didn't research it.)

I wonder if missing "that" bothers others? Should we go a quick ask in the EOWG telecon or survey?

If not, I'm OK with leaving it.

**Comment by nitedog** [comment]
I stumbled over missing "that" (and maybe also "the" and others but don't recall exactly) here and there. I'm not sure if it is grammatically more difficult to parse, or if I'm just too used to the usual WAI style. I would also be curious on other people's reactions.

**Comment by iadawn** [comment]
As far as I can determine, 'that' isn't grammatically required as 'ensure' has an implicit 'that' within it. I have no problem adding it thought it it makes it easier to read.

Could you specify where you spotted a missing Oxford comma?

**Comment by yatil** [comment]
👍

**Comment by iadawn** [comment]
Following discussion between Shawn and Kevin, have changed every 'Ensure' to include a 'that'.

Any errant Oxford commas can be tracked down and returned to the appropriate sentence.
