### ISSUE TITLE
Mouse hover & keyboard focus the same?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#105]
Ref: Tips for Designing, Ensure interactive elements are easy to identify
http://w3c.github.io/wai-quick-start/designing.html#ensure-interactive-elements-are-easy-to-identify

Is it really important to "provide distinct styles for mouse hover, keyboard focus, and touch-screen activation" -- that is, each needs to be different?

Wouldn't it be best of the mouse hover and the keyboard focus are the same?

**Comment by nitedog** [comment]
I think it is best to have them different. Responses from the Mobile TF show that activation style does help on touch interfaces, and is included in the BBC guidelines for example. Some people use pointing devices and touch screens at the same time (eg. laptops with touch screens), so having the same style would be confusing ("am i just hovering or did i press by mistake?").

Maybe the vertical spacing and the vivid colors of the examples are making it too distracting?

**Comment by yatil** [comment]
:hover and :focus should _at least_ be the same visual design, yet :hover can be more subtle as the user is already pointing at the link with their mouse. When using the keyboard, it is not entirely clear where you need to look next, so having a more visible outline is recommended.

**Comment by iadawn** [comment]
Based on discussion between Shawn and Kevin, I will explore using various different background colors to highlight :hover and :focus in different ways.

**Comment by iadawn** [comment]
Alternative styling suggested in b7f1df4b3eff1483d98323422bc9e6ec085eca22.

Closing this issue, if there are still problems, please feel free to reopen.
