### ISSUE TITLE
additional example for headings & spacing

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-quick-start#107]
"Use headings and spacing to group related content" would benefit from an example, I think.

**Comment by iadawn** [comment]
[EO Meeting 10 Jul](http://www.w3.org/2015/07/10-eo-minutes.html): Resolved to create a draft example for use headings and spacing

**Comment by slhenry** [comment]
The current draft example only adds headings and lists. That is primarily a writing task.
If there is an example in designing, it should focus on whitespace and proximity mostly, and maybe headings styling a bit. (Sorry I didn't communicate that well enough in the EOWG telecon.)

Idea:
1. before:
* include an illustration that doesn't have good proximity, e.g., it's on the right across two sections of text so you can't tell which section of text it applies to
* include the subheadings but without space before them
* (don't address lists in designing, that's more writing)
2. after
* has space before subheadings
* maybe even has left margin of text indented so the headings are even more clear (like we did in these Tips :)
* has the illustration clearly placed within a section

**Comment by iadawn** [comment]
I have tried to create an alternative example closer to what you are suggesting. This was added in 9e20b71.

If this is not quite right, either a session with WebEx's whiteboard, or perhaps we could collaborate using an online wireframing tool such as [Mockflow](http://www.mockflow.com/)

**Comment by slhenry** [comment]
sorry - one more minor thing: the image should be the same size on the before as it is on the after - and maybe the headings the same size, too?

**Comment by nitedog** [comment]
agree on the headings sizes - actually the "before" sub-headings seem larger (= easier to distinguish) than the "after" sub-headings. i suggest using the same sizes or reversing the sizes of before and after.

**Comment by iadawn** [comment]
Changed to using the same sizes for before and after. They were originally different to subtly suggest that heading size matters as well.

**Comment by iadawn** [comment]
Closing issue. If there is anything else to consider, please do reopen.
