### ISSUE TITLE
move Grouping tip up

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#108]
Tips for Designing: Use headings and spacing to group related content
http://w3c.github.io/wai-quick-start/designing.html#use-headings-and-spacing-to-group-related-content

This is an easy one and an important one, so I propose that it goes higher in the list. [low]

**Comment by iadawn** [comment]
I will close this off as ordering will be captured in [EOWG Weekly Survey - 13 July 2015](https://www.w3.org/2002/09/wbs/35532/EOWG13July2015/)
