### ISSUE TITLE
Writing Tips - overall tweaks to wording and order

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#113]
Several suggestions on order and wording (not all minor edits are called out in [brackets]):
* Provide informative, unique page titles ["provide" here because sometimes writers are not coding them themselves, but giving them to the coder]
* Use headings to structure text [hum, it's more than structure. it's also break up and introduce and such...]
* Keep content clear and concise [I don't like "keep" maybe "Write clearly and concisely" or ?]
* Avoid overly complex words and phrases [tersified out "using" :). probably delete "and phrases" 'cause that's already covered by clear and concise?]
* Make link text meaningful
* Provide text alternatives for images
* Provide transcripts and captions for multimedia [deleted "content"]
* Expand acronyms on first use

**Comment by iadawn** [comment]
> Provide informative, unique page titles ["provide" here because sometimes writers are not coding them themselves, but giving them to the coder]

Done. Although note that the tips are targeting the activity not the role

> Keep content clear and concise [I don't like "keep" maybe "Write clearly and concisely" or ?]

Note discussion in #29 regarding wording for this

> Use headings to structure text [hum, it's more than structure. it's also break up and introduce and such...]

Suggesting: 'Use headings to convey meaning and structure'

I haven't done anything with order yet as I assume this will be reflected in the rating survey.

Other suggested minor editorial changes have been included.

**Comment by slhenry** [comment]
RE: "I haven't done anything with order yet as I assume this will be reflected in the rating survey." May I suggest that you take a first pass at re-ordering them -- before the survey goes out? Please see my previous comment on an ordering approach that included a suggestion to consider putting the easiest to do and the easiest to understand near the top.

**Comment by slhenry** [comment]
... and most important ;)

**Comment by iadawn** [comment]
I have rearranged to your suggested order. I don't feel that the titles is necessarily the most important though. Titles are extremely beneficial for some assistive technology users but clear and simple text is extremely beneficial for people with reading disabilities. I don't feel that it is easy to say which is more important.
