### ISSUE TITLE
Writing Tips - Forms

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#114]
Perhaps tip(s) related to forms is relevant to the writing task -- particularly related to Guideline 3.3 Help users avoid and correct mistakes -- but will need thought and differentiation from designing and developing. 

For things like error messages: designing says how they look, but would writing be what the messages say? I note that I had edit suggestions for the wording in the example in the designing tip -- that's a writing task.

Error Identification: 3.3.1... the error is described to the user in text.
Error Suggestion: 3.3.3 ...  the suggestions are provided to the user,

**Comment by iadawn** [comment]
I might suggest something like:

> Write clear and helpful form instructions and errors

**Comment by AndrewArch** [comment]
Kevin, maybe it would be better as "Write clear and helpful form instructions and error explanations" :)

**Comment by AndrewArch** [comment]
Shadi comments during EO meeting:
[[ suggest not focusing this on forms too much - maybe more generally to provide clear guidance where action is required, such as forms ]]

**Comment by iadawn** [comment]
I have included an initial draft tip in 171b9d2 to try to address this.

Relates to [discussion in EO meeting 24 July](http://www.w3.org/2015/07/24-eo-minutes.html#item02).

**Comment by nitedog** [comment]
minor suggestion for consideration: "Ensure that where action is required, such as on forms, instructions and guidance are clear and simple" -> "Where action is required, such as on forms, ensure that instructions and guidance are clear and simple".

**Comment by iadawn** [comment]
Have updated with slight variation on your suggestion. Just tried to front load the 'ensure that instructions and guidance are clear and simple'.

**Comment by iadawn** [comment]
Closing as no other issues. If still discussion please feel free to reopen.
