### ISSUE TITLE
Developing – Remove/replace code validation tip

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#118]
Instead or in addition to code validation, we should point developers to evaluation tools that help them to make the best decisions and add accessibility into their test cases. (I vividly remember that there was a lot of confusion when ARIA was added to the web dev stack and people thought their whole website would be inaccessible as it did not validate with HTML4.)

**Comment by iadawn** [comment]
I might suggest something like:

> Perform quick accessibility checks

**Comment by slhenry** [comment]
I think Eric's point is that there are tools to help understand and check accessibility issues at the code level.

**Comment by nitedog** [comment]
ROUGH suggestion for consideration:

[[
# Ensure compatibility of your code

Make sure your code, especially for web applications, is supported by web browsers and assistive technologies. For example, some HTML5 and WAI-ARIA features might not be supported. Some _evaluation tools_ help you check compatibility.
]]

**Comment by slhenry** [comment]
see also https://github.com/w3c/wai-quick-start/issues/154

**Comment by nitedog** [comment]
having mulled over this a little more, i agree with kevin that this might not be an ideal tip for getting started. at the same time, it may be a useful consideration from the start of any development. i suggest adding it to the list of tips for ranking, to see what others think of its importance vs relevance.

**Comment by iadawn** [comment]
Have considered [responses in survey](https://www.w3.org/2002/09/wbs/35532/EOWG24July2015/results#xq2) and value of tips with regard to the [criteria for tips](https://www.w3.org/WAI/EO/wiki/Quick_Start_Guides/Requirements_Analysis#Criteria_for_Tips) and I am recommending removing the validation and compatibility tips.

**Comment by slhenry** [comment]
+1

**Comment by bakkenb** [comment]
I'm agreeable to removing both.

**Comment by iadawn** [comment]
Both items have been removed. If anyone feels that this is inappropriate, please raise a separate issue. Thanks.
