### ISSUE TITLE
Explore use of icons

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#12]
Raised in [5th Jun EO Meeting](http://www.w3.org/2015/06/05-eo-minutes.html)

**Comment by iadawn** [comment]
I would like to use icons from an existing open source icon library. This does limit the selection a bit, but it means that it is quicker to create SVG versions of the icons and a bit easier to implement them.

Example libraries are:

* [Font Awesome] (https://fortawesome.github.io/Font-Awesome/)
* [icoMoon](https://icomoon.io/)

This means that the task is to select six icons that represent:

* Designing
* Writing
* Developing
* Evaluating
* Managing
* Advocating

**Comment by slhenry** [comment]
a rough mockup of how icons *might* be placed on the overview page: <http://www.w3.org/WAI/EO/Drafts/qst-1slh.html> and the Tips pages <http://www.w3.org/WAI/EO/Drafts/qst-manage2>

**Comment by iadawn** [comment]
Possible alternatives:

## Evaluating

Note: I am avoiding the checkbox or checkmark as I feel that this too strongly suggests a checkbox exercise or approach.

Note: These icons are all taken from iconmoon.io, unlike the existing ones which are from Font Awesome. I have not checked if the other icons used exist in the same iconmoon.io icon set. Ideally all icons should come from the same set.

![Tachometer](http://w3c.github.io/wai-quick-start/images/meter-9d41f7e4.png): Suggestive of measuring things
![Clipboard](http://w3c.github.io/wai-quick-start/images/clipboard-485103eb.png): Indicating the assessors checkboard

## Managing

![Map](http://w3c.github.io/wai-quick-start/images/map2-9ef65af4.png): Suggesting that managing involves an element of deciding and planning direction
![Tools](http://w3c.github.io/wai-quick-start/images/tools-89aa69b0.png): Suggestive of gathering and preparing the tools to begin a body of work
![Person with a tie](http://w3c.github.io/wai-quick-start/images/user-tie-a7c31be6.png): Managers wear ties!

**Comment by iadawn** [comment]
## Designing

Consider using a compass e.g. ![Compass](http://png-3.findicons.com/files/icons/2711/free_icons_for_windows8_metro/512/drafting_compass.png)

**Comment by iadawn** [comment]
## Evaluating

Consider also magnifying glass over computer screen or document. Also consider clip board without checkmark.

**Comment by iadawn** [comment]
## Advocating

Megaphone is ok... although see if can find one that is not an electric one.

**Comment by iadawn** [comment]
I have prepared a temporary page to [show a variety of icon choices](http://w3c.github.io/wai-quick-start/sample.html).

I would say that I have a general preference for the Font Awesome icons as they are clean, really easy to implement, and come with no attribution requirement in the licensing. I also have a medium preference towards the more simple icons as they require less interpretation and scale well when they are used in smaller areas.
