### ISSUE TITLE
Use lists rather than sentences

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-quick-start#120]
Suggested as it aids scanning written content and comprehension. E,g,

Blah blah. This is influenced by factors including location, literacy, age, cultural considerations, and access to communication or media channels.

vs.

 Blah blah. This is influenced by factors including:
* location
* literacy
* age
* cultural considerations, and
* access to communication or media channels.

**Comment by iadawn** [comment]
Closing in light of discussion around #158
