### ISSUE TITLE
Examples for Keep content clear and concise

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#129]
Tip: [Keep content clear and concise](http://w3c.github.io/wai-quick-start/writing.html#keep-content-clear-and-concise)

**Comment by AndrewArch** [comment]
Example is fine - maybe "If you're involved ..." rather than "If our client is involved ..." ?

**Comment by iadawn** [comment]
From @bakkenb:

>  I like the example that is currently implemented. I think the audience will clearly see what you mean by complex content vs. simple content.

**Comment by sharronrush** [comment]
yes this example is fine

**Comment by slhenry** [comment]
Personally, I think the example is more distracting than helpful.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xwriteTp):

> Minor, but I found the phrase "Once we obtain information that causes us to understand the causality" distracting because it seemed unrealistic - not a real example, but like you added the phrase to make it complex on purpose.

> Maybe rewrite the complex side to read: "In the event of a vehicular collision, a company assigned representative will investigate to ascertain the cause and extent of damages to property belonging to the parties involved. Once  cause, damages, and responsibility have been established, we will assign monetary remuneration accordingly."
