### ISSUE TITLE
Examples for Avoid using overly complex words and phrases

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#130]
Tip: [Avoid using overly complex words and phrases](http://w3c.github.io/wai-quick-start/writing.html#avoid-using-overly-complex-words-and-phrases)

**Comment by AndrewArch** [comment]
see some examples at https://www.dto.gov.au/design-guides/guide/online-writing

**Comment by iadawn** [comment]
From @bakkenb:

>  I believe tip 1 and tip 2 are separate issues and should be kept separate. Because of this, I think this tip SHOULD have an example or two that shows the focus here is on complex words and not
complex writing (tip 1). I think medical, legal and/or financial jargon could be used as the example.

**Comment by sharronrush** [comment]
I agree that the two concepts are different, but it is nuanced and I believe this one will be difficult to illustrate with an example and the simple statement of general guidance should be OK on its on.

**Comment by slhenry** [comment]
I think this one does *not* need an example.
