### ISSUE TITLE
Examples for Provide headings to structure text

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#131]
Tip: [Provide headings to structure text](http://w3c.github.io/wai-quick-start/writing.html#provide-headings-to-structure-text)

**Comment by AndrewArch** [comment]
I agree that an example would be too long to include for this tip - instead link to the [tutorial](http://www.w3.org/WAI/tutorials/page-structure/headings/) for examples (is this the incentive to finish it?)

**Comment by iadawn** [comment]
From @bakkenb:

>  I do not think an example is necessary here. The tip text has examples that area clear and understandable.

**Comment by vmmiller** [comment]
Maybe a simple example in html would be useful.

**Comment by sharronrush** [comment]
If we use an example, it would be useful to demonstrate the difference for the screen reader user between of using heading markup for visual effect and the actual usefulness of structured text for random access to content that is close to that of sighted users who skim for their target.

**Comment by slhenry** [comment]
I think this doesn't need an example. To provide an effective example (e.g., as Sharron suggests), would be too complex.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xwriteTp):

> I support a full headings example to be crystal clear (H1,H2,H2 is enough). Quirky headings are good.  If you tell a very short story or joke as your example, people may remember it better.

**Comment by iadawn** [comment]
Agreed to try to come up with a good, succinct example

**Comment by slhenry** [comment]
I continue to think that we cannot come up with a good, succinct example -- because by it's nature it requires lots of text to make the point. Possibly it would work to make the text really tiny, more like a wireframe like the example under http://w3c.github.io/wai-quick-start/designing.html#use-spacing-and-headings-to-group-related-content

Yet I still think this Tip doesn't warrant an example.

**Comment by iadawn** [comment]
Closing as headings example was considered suitable by EO ([meeting of 7 August](http://www.w3.org/2015/08/07-eo-minutes.html))

**Comment by nitedog** [comment]
I like the current example but do not recommend using the (AFAIK outdated) "javascript: return false" hack. I suggest linking to a separate page with the example, in case javascript is not activated, and catching the event in case it is activated, to launch the overlay - progressive enhancement ;)

**Comment by iadawn** [comment]
Rather than a separate page I have improved the modal script to add in the classes that style the modal windows and changed the return false to be an in-page anchor. This means that no javascript will keep the content visible (albeit not wonderfully pretty) and the link will still go to the correct place.

A possible move on from this is to only have the links show if JS is available, but that is much more involved and arguably not worth the effort.

**Comment by vmmiller** [comment]
+1 current example (August 20)
