### ISSUE TITLE
Examples for Use informative and unique page titles

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#132]
Tip: [Use informative and unique page titles](http://w3c.github.io/wai-quick-start/writing.html#use-informative-and-unique-page-titles)

**Comment by AndrewArch** [comment]
sorry - no concrete suggestions

**Comment by iadawn** [comment]
From @bakkenb:

>  If an example is needed here, maybe one like the Spacing and Headings tip from the Designing page. I am on the fence whether this needs an example or not. Editor's discretion.

**Comment by sharronrush** [comment]
A good page title tells your users what page they are on and what that page is for. If relation to other parts of the site are to be conveyed, the title should start with most specific information and end with most general. For example:
Minny Morton - Staff profiles - About Us - XYZ Corp

**Comment by slhenry** [comment]
I think examples might be useful here.
(fyi, check put the examples in Easy Checks under "Tips" http://www.w3.org/WAI/eval/preliminary#title )
Maybe something like Sharrons above -- also with a bad example of it. And also an example of a page in a multi-step process.

**Comment by iadawn** [comment]
Agreed to include example

**Comment by iadawn** [comment]
Reopening as styling of examples is still problematic as discussed in [EO meeting of 7 Aug](http://www.w3.org/2015/08/07-eo-minutes.html#item04).
