### ISSUE TITLE
Examples for Provide transcripts and captions for multimedia content

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#134]
Tip: [Provide transcripts and captions for multimedia content](http://w3c.github.io/wai-quick-start/writing.html#provide-transcripts-and-captions-for-multimedia-content)

**Comment by AndrewArch** [comment]
Could initally show how to link to video with alternative link to transcript
Could include real videos when the TF has completed their work :)

**Comment by iadawn** [comment]
From @bakkenb:

> I don't think an example is needed for this tip.

**Comment by vmmiller** [comment]
An example as described above could be useful.

**Comment by sharronrush** [comment]
I think the statement is clear, not sure it needs an example, but don't feel strongly

**Comment by slhenry** [comment]
I think do not want an example for this one. It's clear enough without it, and any example would be fairly complex and risk being especially distracting.

**Comment by iadawn** [comment]
Agreed not to include an example as it may be too complex.

If anyone feels that there really should be an example, please re-open and comment.
