### ISSUE TITLE
Examples for Use progressive enhancement

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#136]
Tip: [Use progressive enhancement](http://w3c.github.io/wai-quick-start/developing.html#use-progressive-enhancement)

Note in this case there is no suggested example. Should there be one? If so, what?

**Comment by iadawn** [comment]
From @bakkenb:

> No example needed for this tip.

**Comment by sharronrush** [comment]
I would like an example here an think several could be adapted from Designing with Progressive Enhancement from Filament Group https://www.filamentgroup.com/dwpe/ Let me know if you want me to pick one like how to display a rating star sytem

**Comment by slhenry** [comment]
I do not think an example is needed for this one. (It seems any example would be pretty complex.)

**Comment by iadawn** [comment]
Agreed to no example as would be too complex.

@sharronrush, appreciate your ideas and if you feel strongly that there should be an example, please re-open issue.
