### ISSUE TITLE
Examples for Adopt a responsive design approach

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#137]
Tip: [Adopt a responsive design approach](http://w3c.github.io/wai-quick-start/developing.html#adopt-a-responsive-design-approach)

**Comment by iadawn** [comment]
From @bakkenb:

> I think an example here would be good. Something that shows how very different content will look on various viewports if designed responsively. This may be one where you could show a bad example of
usability on a small viewport if responsive design is not implemented (or implemented poorly).

**Comment by sharronrush** [comment]
An example here will be important.
* typo note: ...such as on mobile devices and tables / should be ...such as on mobile devices and tablets

**Comment by slhenry** [comment]
Maybe an example would be good here. Would it be the same as the example for http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes ?

**Comment by iadawn** [comment]
Not necessarily as it would be more concerned with how to structure code (in this case CSS @media queries) to bring about the design changes shown in that example.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xdevelTp):

> I see much value in an example in a new window that they can resize.

**Comment by iadawn** [comment]
Agreed to include example
