### ISSUE TITLE
Examples for Use mark-up to convey meaning and structure

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#138]
Tip: [Use mark-up to convey meaning and structure](http://w3c.github.io/wai-quick-start/developing.html)

**Comment by iadawn** [comment]
From @bakkenb:

> Because of my lack of knowledge, I am not sure whether this tip needs and example or not. An example would probably help me understand the tip more, but that is probably because I am
not a developer. Whatever EO collectively decides is fine with me.

**Comment by sharronrush** [comment]
Lists are a good form to use as an example since the user gets information about how many items are related, when the list ends etc that are provided visually to the sighted reader but not at all to the blind one unless the proper mark-up is used.

**Comment by slhenry** [comment]
I think this tip is clear enough without an example. Also, any example would 1. take up a lots of space and potentially be complex, &/or 2. be just the tip of the iceberg (pun intended) of the broad issues this tip covers.

(Again, I agree with Sharron that that's a good point for training, but it's too much to cover in this Tips page.)

(In the olden days, it would be appropriate to have a BAD-GOOD example set with <font> instead of <hx> -- but I don't think that's necessary these days.)

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xdevelTp):

> I think we need a few examples here - it's a good general tip, but without a starting point of several solid examples, the tip means little.

**Comment by iadawn** [comment]
Agreed to work up an example that effectively conveys the tip without being too big or complex

**Comment by nitedog** [comment]
I *love* the first example - it uses both HTML5 and WAI-ARIA, and is clear and concise!

I think the second example is not worth the space it takes up. I suggest dropping the second.

**Comment by nitedog** [comment]
re-opening, unless this issue of the second example has been discussed and agreed upon with EO.

**Comment by iadawn** [comment]
Examples in Developing have not been discussed as yet. Probably this week.

Just to give background on the second example. I was conscious that many of the examples are related to forms. I wanted to highlight other semantic elements that HTML5 provides that are not forms related.

**Comment by metzessible** [comment]
I like the example with Superbear, because it highlights the Outline which is largely underused. 

Just one question though. In [Issue #139](https://github.com/w3c/wai-quick-start/issues/139), ARIA labels were suggested, but the response was that it might be out of the scope for a beginner topic. Why is ARIA acceptable here and not there? Thanks in advance for clarification.

**Comment by iadawn** [comment]
@metzessible A fair question. I think that in 139 the tip can be simply achieved using straight forward HTML markup. I am hesitant about adding a more complex example and felt it was better left for the Tutorials to explore that area.

In this example, and in a few others, I have included bits of ARIA that add just a little bit extra information or suggest a different way to do things without going into them too much.

If you have concerns with this approach, please do add them here or they can be discussed in EO meeting.

**Comment by slhenry** [comment]
"Provide structure and meaning with HTML5 elements" I wonder if people will get hung up on only "HTML5 elements". What if I'm not doing HTML5 yet? We still want them to use headings, lists, etc.

**Comment by iadawn** [comment]
This was a reword of an idea provided by Andrew in EO meeting.

I don't have a strong feeling but it would be good to be (subtly) suggesting to readers that HTML5 is the way to go.

**Comment by slhenry** [comment]
I think previously you had just "HTML5 elements", and in the telecon we suggested including "structure" -- thus Andrew's suggestion. The example includes HTML5 elements and I think that's subtle enough. ;-)

I think it would be safest to just say "Provide structure and meaning with HTML elements" <stream-of-conscious> ... hum what if it's not an HTML doc ... well, this is just one example... the next one's caption is "Search field using WAI-ARIA" </s-o-c> so probably better as:
"Structure and meaning provided with HTML elements"
