### ISSUE TITLE
Examples for Associate all form elements with labels

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#139]
Tip: [Associate all form elements with labels](http://w3c.github.io/wai-quick-start/developing.html#associate-all-form-elements-with-labels)

**Comment by iadawn** [comment]
From @bakkenb:

> I think a code snippet example would be good here. A visual could be added as well if it is helpful and appropriately matching the snippet.

**Comment by sharronrush** [comment]
an example could address the confusion that people often have between the onscreen  text and what it means for that text to be explicitly tied to the form input.  So, for example if you did something like:
<label for="breed">Your Dog's Breed: </label>
<input type="text" name="breed" id="breed" />
and showed the rendered form, you could explain that a screen reader will say “Your Dog's Breed colon edit. Type in text”.

**Comment by slhenry** [comment]
I think the current example is fine. It's short and clear.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xdevelTp):

> Perhaps show the offscreen label example too.  Why not discuss aria labels?

**Comment by iadawn** [comment]
Agreed to include example.

James: I will consider how to include an off-screen label example. More in-depth discussion on ARIA may be a bit beyond the introductory tips.

**Comment by reinaldoferraz** [comment]
I was thinking about inserting a code example related to associating labels implicitly, because some CMS provide forms fields like <label>Name<input type...></label>,  but I'm not sure if it is really helpful and necessary as a tip example.

**Comment by iadawn** [comment]
The forms tutorial includes [information on implicit labels](http://www.w3.org/WAI/tutorials/forms/labels/). I think the aim with the tips is to try not to repeat too much of the tutorials and ensure there are appropriate links to them.

Do you think that is sufficient or would you still prefer to see an example?

**Comment by nitedog** [comment]
I think the example is good too.

Minor comment on the wording, though: "Position the <label> element offscreen using CSS when the design does not include a visible label" -> "If needed, hide the <label> visually using CSS [when the design does not include a visible label]" - rationale: I think that technically the "offscreen" technique is outdated because it is caught by some ATs, and the most current approach is to display the content in a 1x1 pixel "onscreen" - maybe check with others on this.

**Comment by iadawn** [comment]
Actually, one thought I had is to dump the off-screen CSS completely and mention `aria-label` instead. That is much more appropriate, should be more accessible, and isn't really a 'hack' of any sort at all.

Thoughts?
