### ISSUE TITLE
Examples for Help users avoid and correct mistakes

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#140]
Tip: [Help users avoid and correct mistakes](http://w3c.github.io/wai-quick-start/developing.html#help-users-avoid-and-correct-mistakes)

**Comment by iadawn** [comment]
From @bakkenb:

>  I think there should be an example here. Since the Designing page has an example showing what the mistake is and what should be corrected, I think this example should focus on the "avoidance"
of the mistake. The first example is good (password or date), I cannot tell you how many times I have lost data in forms when filling out a multi form page simply because my password did not conform to the requirements, and the requirements were not clearly given in the first place. Frustrating.

**Comment by sharronrush** [comment]
Yes, suggested examples are good

**Comment by vmmiller** [comment]
An example would be important.

**Comment by slhenry** [comment]
I'm not sure on this one. I think we do *not* want a long example like in Designing.

Possibly a short example of " instructions for password requirements or date format" would be helpful.

(What about in the Learn More links, we link to http://w3c.github.io/wai-quick-start/designing.html#provide-clear-feedback and maybe http://w3c.github.io/wai-quick-start/writing.html#provide-clear-instructions )

**Comment by iadawn** [comment]
Agreed to include an example

**Comment by slhenry** [comment]
Perhaps change from:
"For example, (02) 1234 1234"
to:
"Format: (02) 1234 1234"
?

**Comment by iadawn** [comment]
I would prefer to keep the 'For example' wording as this is an example, not an indication of format. There is an implicit format but a format would be expressed in a different way, for example, (dd) dddd dddd.

**Comment by sharronrush** [comment]
+1 to kevin

**Comment by slhenry** [comment]
fine. I don;t feel strongly.
