### ISSUE TITLE
Examples for Reflect the reading order in the code order

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#141]
Tip: [Reflect the reading order in the code order](http://w3c.github.io/wai-quick-start/developing.html#reflect-the-reading-order-in-the-code-order)

**Comment by iadawn** [comment]
From @bakkenb:

>  I like the suggested example for this tip.

**Comment by sharronrush** [comment]
I don't quite see how the suggested example demonstrates the principle.  Maybe I would just have to see it. Seems like you could show something that looks like it would read a certain way but when you turn off style sheets, you see that the reading order is kattywumpus (a highly technical term)

**Comment by slhenry** [comment]
I do not think we need an example for this tip. I think the text is clear without it. An effective example would take up a lots of space and be pretty complex.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xdevelTp):

>  I think the example can be enhanced if we craft the visual design in a way that places main content elements next to each other, maybe with contextual information alongside it so it would be hard to get a
consensus on the natural code order were you not to evaluate the content. 

> This will highlight the value of natural code order.  E.g., something to buy: image on left, buy button and price below it, title on right, detailed description below that.  I would argue (following the "Front-load important messages" tip from writing) that the correct order is 1. title 2. image
(with good alt) 3. description, 4. buy button.

**Comment by iadawn** [comment]
Agreed to draft an example and revisit

**Comment by nitedog** [comment]
I think it is a problem using the real brand name "All Star" - just switch to "My Boot" or "Space Boot" or whatever is obviously fictional but still comprehensible as an example product.

**Comment by slhenry** [comment]
Suggest change color of "Code order does not reflect reading order:" to black or otherwise not the WAI rust

**Comment by iadawn** [comment]
Changed
