### ISSUE TITLE
Examples for Provide meaning to non-standard interactive elements

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#142]
Tip: [Provide meaning to non-standard interactive elements](http://w3c.github.io/wai-quick-start/developing.html#provide-meaning-to-non-standard-interactive-elements)

**Comment by iadawn** [comment]
From @bakkenb:

>  Again, because of my lack of knowledge, I am not sure whether this tip needs and example or not.
An example would probably help me understand the tip more, but that is probably because I am not a developer. Whatever EO collectively decides is fine with me.

**Comment by sharronrush** [comment]
The only way I can imagine providing an example is to show code with no ARIA and then caption the image with the screen reader output demonstrating that the user will not know what the widget purpose is.  Accomplishing the useless widget should be the same thing with the proper ARIA captioned with screen reader output that IS useful

**Comment by slhenry** [comment]
I do not think we want an example for this one.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xdevelTp):

> lots here, should we define the few most common and show aria for them?  this, like markup to convey meaning, is not much of a tip without examples...

**Comment by iadawn** [comment]
Agreed to provide more details on what the example may be

**Comment by iadawn** [comment]
Added in an example slider. Couple of things worth noting:

1. This could be achieved with `<input type="range">` but without the styling options.
2. This does not include the scripting required to make it work. This can be added if necessary.

**Comment by iadawn** [comment]
Second example creating a switch from a `<div>`. Again:

1. This could be done in pure CSS using a hidden checkbox
2. Scripting has been included for this, because it was a touch easier

**Comment by nitedog** [comment]
i love the examples but *strongly suggest dropping the slider one* - the button example is totally sufficient to illustrate the tip, while the slider one is considerably more complex and delves too much into WAI-ARIA details that are more apt for the tutorials rather than this resource.

**Comment by iadawn** [comment]
Happy to remove that... the JavaScript was going to be quite involved and I hadn't done it as yet.

**Comment by bakkenb** [comment]
Not understanding this one. Over my head development wise. Something doesn't seem to match up between the rendered and the snippet.  I will wait for discussion during meeting to look for clarification.

**Comment by slhenry** [comment]
change color to not rust :-)
