### ISSUE TITLE
Examples for Ensure that all interactive elements are keyboard accessible

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#143]
Tip: [Ensure that all interactive elements are keyboard accessible](http://w3c.github.io/wai-quick-start/developing.html#ensure-that-all-interactive-elements-are-keyboard-accessible)

**Comment by iadawn** [comment]
From @bakkenb:

>  I don't feel an example is needed for this tip.

**Comment by sharronrush** [comment]
Could use the common example where expand and collapse controls can't be operated from the keyboard

**Comment by slhenry** [comment]
I don't think we want an example for this one.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xdevelTp):

> I'd change "such as menus, collapsable accordions, or media players." to "such as menus, mouse-over info, collapsable accordions, or media players."  Maybe an example showing the use of keyboard events along with mouse events vs. a bad one that only uses mouse events.

**Comment by iadawn** [comment]
Agreed to include an example as suggested by James

**Comment by iadawn** [comment]
Added in example to show a menu open/close. Couple of things to note:

1. Using `<button>` instead of `<div>` means the keydown event bind would not be required. An alternative example where something required `<div>` to be used might be relevant. Alternatively, make note that using `<button>` would be a better idea in the long run.
2. Need to think about how the various code snippets are presented. Far too much information on the page.

**Comment by nitedog** [comment]
excellent example but agree on the verbosity of the code snippets. I suggest dropping these code snippets - real developers will look into the source code anyway ;) ...*if needed*, maybe add a small footnote and/or a link to a separate source code file (eg. "See source code for more information on how to handle keyboard access within the scripts" or "See [link]full source code".

**Comment by iadawn** [comment]
What I have done is shown only the relevant JavaScript code; the stuff about event handling. As you say developers will be able to find the full JS easily enough.

I don't know that a separate link to a full example is necessary. This isn't a full tutorial, and aims to start readers thinking about the items and provide them with some direction. Happy to discuss this though.
