### ISSUE TITLE
Examples for Check that your code validates

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#144]
Tip: [Check that your code validates](http://w3c.github.io/wai-quick-start/developing.html#check-that-your-code-validates)

Note in this case there is no suggested example. Should there be one? If so, what?

**Comment by iadawn** [comment]
From @bakkenb:

>  I don't feel strongly that an example is needed, but maybe you could show some invalid code that works fine on a desktop or laptop with a basic screen reader, but when a specific AT is introduced, such as a refreshable Braille display, the code is not sufficient and can introduce access barriers. Just an idea of trying to show how code may be good enough to "work" but if it is not valid it may not "work" in all situations vs. code that was validated. This idea may be to complex.

**Comment by sharronrush** [comment]
Not sure an example is needed, other than a link tot he W3C validator :)

**Comment by vmmiller** [comment]
I don't feel strongly about an example.  But if an example would be required, possibly, a snapshot of errors produced from the validator would be effective.

**Comment by slhenry** [comment]
I don;t think we want an example for this one, and I can't even imagine an effective example.

**Comment by iadawn** [comment]
Agreed that no example necessary
