### ISSUE TITLE
Example for Make link text meaningful

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#148]
Tip: [Make link text meaningful](http://w3c.github.io/wai-quick-start/writing.html#make-link-text-meaningful)

**Comment by iadawn** [comment]
From @bakkenb

> I do not think an example is necessary here. The tip text has examples that area clear and understandable.

**Comment by sharronrush** [comment]
If an example is considered useful, you could adapt this one where each product on this page http://www.verizonwireless.com/tablets/ has Learn More and the links list looks like this 
![learn-more](https://cloud.githubusercontent.com/assets/6991827/8858603/fb153500-313d-11e5-8ec3-c5ca56fcb56b.jpg)
What I like about this example is that it shows the difference between the ones where there is "Learn More about xxx" contrasted with the other "Learn More" links that give no context.

**Comment by vmmiller** [comment]
Good example, Sharon!

**Comment by slhenry** [comment]
I think we do not need a separated-out example here (beyond the examples in the description).

I agree Sharron's example is awesome for training, tutorials, etc. (and I'm going to copy it ;-); however, I think it's too much for this Tips page.

**Comment by iadawn** [comment]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xwriteTp):

> To think about:  I know some are against the "why" but I think that without the why, some new devs and writers may just decide to skip a given tip if it's "too hard" e.g., meaningful link text - without the why, they may feel that it's too hard not to use "click here" to be worth the trouble.  ... I know the why is under the "Understanding" links but newbies would not know that unless we tell them.

**Comment by iadawn** [comment]
Agreed to try to come up with a good, succinct example
