### ISSUE TITLE
Edit: Writing: Link text

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#149]
Suggested edit:
Write link text so that it makes sense out of context. Choose link text that clearly and accurately describes the link target. Avoid using link text such as 'click here', 'learn more', or 'read more'. Indicate the document type and approximate size in the link text when the link target is not HTML.

**Comment by iadawn** [comment]
This has been subjected to a number of edits. I will close this issue and if you have any further comments feel free to raise a new issue.
