### ISSUE TITLE
Edit: Writing: Page Title

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#150]
Edit suggestion:
Provide a unique title for every page. Useful titles clearly and briefly summarize page content or purpose, and distinguish it from other pages. If repetitive content, such as the organization's name, is to be included in the page title, put unique content first with repeated content following. For pages that are part of a group, such as a multi-step process, include the stage in the page title.

**Comment by iadawn** [comment]
This has been subjected to a number of edits. I will close this issue and if you have any further comments feel free to raise a new issue.
