### ISSUE TITLE
Tip: Table markup!

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#152]
Needs to be covered. At this point, I don't feel strongly about it being a separate tip or being clearly included in "Use mark-up to convey meaning and structure". Would be good to get EOWG perspectives on this.

**Comment by iadawn** [comment]
[EO Meeting 24 Jul](http://www.w3.org/2015/07/24-eo-minutes.html): Agreed to explicitly mention table mark-up into the meaning and structure tip and not have a specific tip.

**Comment by iadawn** [comment]
Added in specific mention of tables into initial sentence and suggested including a **simple** table example. If happy, please feel free to close issue.

**Comment by slhenry** [comment]
will submit minor tweak as pull request.
will submit addition of pointer to table tutorial in pull request.
as mentioned earlier, do *not* think we want a table example here
