### ISSUE TITLE
Focus order

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#153]
I'm not sure that the current "Reflect the reading order in the code order" adequately or appropriately addresses Focus Order: 2.4.3.

**Comment by iadawn** [comment]
This particular tip wasn't exclusive to 2.4.3. In general, when creating the tips, it wasn't approached from the perspective of the Guidelines first but from issues that were felt to arise and lead to problems. For many it is likely that there is a one-to-one relationship, this is an example where this is not the case.

In response to your specific concern, would adding a bit more with regard to focus order help or are you suggesting removal or this tip entirely?

**Comment by slhenry** [comment]
I think we probably need to address 2.4.3. more explicitly and clearly. I'm not sure that "Reflect the reading order in the code order" is the right focus. I wasn't suggesting removing the tip.

**Comment by LydiaHarkey** [comment]
Developers may misinterpret the word 'Reflect' the reading order as an awareness versus verifying the reading order

**Comment by nitedog** [comment]
I think the sentence "This can be checked by removing CSS styling and comparing the order of the content with the visual hierarchy of the page" needs a qualifier, like "can often be checked" or "one way of checking can be done by ..." - removing CSS does not always work, depending on the page complexity, scripting, structure, etc.

**Comment by slhenry** [comment]
fyi, I'm [mildly] uncomfortable with the approach of "This can be checked" because that seems like a task for the later stage of developing, rather than an approach for starting out.

**Comment by sharronrush** [comment]
But it is not true that we are providing tips for people getting started in *accessibility,* not necessarily at the start of a specific project? So it less relevant where they are in the development process and more relevant that they are getting started in thinking about accessibility.

**Comment by bakkenb** [comment]
How about adding another few words here? "One way to check this during development is to remove CSS styling..."

**Comment by iadawn** [comment]
Current wording is:

> One way to check this is to remove <abbr>CSS</abbr> styling and comparing the order of the content with the visual hierarchy of the page.

If there are still concerns with this, please add a comment, otherwise I will close the issue.

**Comment by yatil** [comment]
I like it, but I would like to have a proper (abbreviated) alt text added. Having just an ellipsis there may be a signal that you don’t need alt in this instance and might be confusing. — _For editor’s discretion._

**Comment by iadawn** [comment]
@yatil I am a little bit reticent to add in the full alternative text. I think it will make it harder to see the point of the example, which is about the code order. Also, if I put in the alternative text, would the same argument not apply to the additional text in the `<p>` and the href? Finally, the code in the example itself includes the full alternative text.

Closing without change. If you feel strongly about this, please do reopen.

**Comment by metzessible** [comment]
Is there a chance we can *slightly* change the label of the examples? For example, instead of saying in bold, "Code order does not reflect reading order" or "Code order reflects reading order", include headings that say, "Example of incorrect reading order" (I'm not wordsmithing, but this is the gist), and "Example reflecting reading order" with a new paragraph under each one.

**Comment by yatil** [comment]
Reopen to ping @iadawn for @metzessible’s comment. (Should probably be a new issue?)

> Closing without change. If you feel strongly about this, please do reopen.

I don’t feel strongly.

**Comment by iadawn** [comment]
Changed based on e098926

If there are still concerns with this, please do reopen.

**Comment by yatil** [comment]
👍
