### ISSUE TITLE
Check that your code validates

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#154]
We all know that it's best practice for code to validate. However, it is not a WCAG 2 requirement -- only two specific aspects are included in WCAG 2. How much of an issue is invalid markup to real-world accessibility? If not so much, then maybe do not include this tip.

**Comment by sharronrush** [comment]
+1

**Comment by iadawn** [comment]
As I understood it, [4.1.1 Parsing](http://www.w3.org/TR/WCAG20/#ensure-compat-parses) requires that code is valid and [Technique G134](http://www.w3.org/TR/2013/NOTE-WCAG20-TECHS-20130905/G134) makes specific reference to it as well.

**Comment by slhenry** [comment]
As I understand it, 4.1.1 is only one aspect of validated code. As I understand it, a web page could meet  4.1.1. and 4.1.2 but still have other validation errors.

**Comment by nitedog** [comment]
valid code - G134 - is *one* way to meet success criterion 4.1.1. however, the *requirement* only applies to specific coding issues that impact assistive technologies.

**Comment by iadawn** [comment]
Closing this issue as #118 is recommending removal of the tip anyway. If the recommendation is changed, then this issue can be revisited.

**Comment by James-Green** [comment]
(I'm not proposing we reopen this issue) just want to add that we currently require that code validate as a general rule because when scaling up, it's less effort than evaluating and signing off on exceptions.
