### ISSUE TITLE
Ensure that all interactive elements are keyboard accessible

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#155]
The description currently starts out "This is easily checked by trying to interact with a page using the keyboard only." Instead, it should provide more specific guidance on what developers need to do, e.g., provide keyboard-triggered event handlers, and maybe example of something like functionality to click and drag items in a list to reorder them also includes a series of controls that allows keyboard users to move items up, down or to the beginning and end of the list.

(The second sentence is wasted words.)

Also, do we want to mention No Keyboard Trap: 2.1.2 in the text? or just in the Learn More. If this is not a common issue any more, then I think we don't mention it in the text.

**Comment by iadawn** [comment]
Significant changes made in this area.

Re: Keyboard Trap: Personally this is not something I see that often. Mostly with Flash. I think it may start to become more involved if we look to explore this.

Closing issue, but do reopen if you feel that Keyboard Trap is something we should consider further.
