### ISSUE TITLE
Make text readable and understandable - first rough pass

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#158]
<article class="tip ">
    <h2 class="attach_permalink" id="@@">Make text readable and understandable</h2>
    <p>Use simple language and formatting, as  appropriate for the context.</p>
    <ul>
      <li><strong>Keep content clear and concise. </strong>Write in short, clear sentences and paragraphs.</li>
      <li><strong>Avoid using overly complex words and phrases. </strong>Consider providing a glossary for terms readers may not know.</li>
      <li><span class="attach_permalink"><strong>Expand acronyms on first use</strong></span>; for example, Web Content Accessibility Guidelines (WCAG).</li>
      <li><strong>Use list formatting as appropriate.</strong></li>
      <li><strong>Provide images  to reinforce information presented in text.</strong></li>
    </ul>
    <aside class="example">
      <h3>Example <em>[@@ first pass, feel free to edit!]</em></h3>
      <div class="two-column">
        <figure>
          <figcaption>Less readable and understandable text</figcaption>
          <div>
            <p class="fail">CPPP: In the event of a vehicular collision, a company assigned representative will seek to ascertain the extent and cause of damages to property belonging to the parties involved. Once we obtain information that causes us to understand the causality, we will assign monetary remuneration accordingly. The resulting decision may result in one of the following options: claim is rejected, claim requires additional information for further processing, claim is partially approved and payment is issued, or claim in approved and payment is issued.</p>
          </div>
        </figure>
        <figure>
          <figcaption>More readable and understandable text</figcaption>
          <div>
            <p class="pass">Claims Processing and Payment Procedure (CPP): If you are involved in a car accident, an agent will investigate. Those findings will determine the payment of claims.<span class="fail"> The resulting decision may result in:</span></p>
            <ul>
              <li>claim is rejected</li>
              <li>claim requires additional information for further processing</li>
              <li>claim is partially approved and payment is issued</li>
              <li>claim in approved and payment is issued</li>
            </ul>
            <p class="pass">[...simple image that shows the process and possible results...]</p>
          </div>
        </figure>
      </div>
    </aside>
  </article>

**Comment by iadawn** [comment]
This is related to #120 and [discussion in EO meeting 24 July](http://www.w3.org/2015/07/24-eo-minutes.html#item03)

**Comment by iadawn** [comment]
This tip has been included in a [copy of the writing page](http://w3c.github.io/wai-quick-start/writing2.html).

Also removed the following tips:

* Keep content clear and concise
* Avoid using overly complex words and phrases
* Provide clear instructions (draft added in #118)
* Expand acronyms on first use

**Comment by sharronrush** [comment]
In the improved version can we avoid the redundancy of "The resulting decision may result in:" and say something like this instead?  

Possible outcomes include:
- rejection of claim, no payment issued
- request for additional information, payment decision on hold
- partial approval of claim, payment issued
- full approval of claim, payment issued
