### ISSUE TITLE
Tip on CAPTCHA

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#159]
Originally from Vicki in survey https://www.w3.org/2002/09/wbs/35532/EOWG13July2015/results#xdev
A few notes in http://www.w3.org/2015/07/24-eo-minutes.html#item09

**Comment by iadawn** [comment]
Suggestion is that if a tip about CAPTCHA is to be include, it not be in multiple places. Designing is one of the less likely spots so removing the label for the moment.

**Comment by iadawn** [comment]
Some pros and cons for this tip:

**Pros**

* Important issue that has a massive impact
* Relevant to many developers

**Cons**

* Difficult to provide clear advice; should one simply not use CAPTCHA?
* Complex and involved topic
* Difficult to create an example
* Many off-the-shelf solutions, so would the developer be the right audience for any advice?
* Lots of alternative approaches, such as honey pots and timed submissions

**Comment by AndrewArch** [comment]
Agree with @iadawn on pros/cons - especially can we just say "don't use"? and how do we talk about the practical alternatives?

The note says "Requiring two different forms of CAPTCHA on a given site ensures that most people with disabilities will find a form they can use" - not acceptable IMHO. See also http://www.smashingmagazine.com/2011/03/in-search-of-the-perfect-captcha/ and http://www.smashingmagazine.com/2014/04/stop-wasting-users-time/ , though reCAPTCHA may be making some progress - http://www.webaxe.org/google-no-captcha-some-progress/

**Comment by LydiaHarkey** [comment]
I recommend that CAPTCHA be located in the developer's section containing resources on how to make CAPTCHA accessible. 

I would not recommend stating 'don't use' as this gives the developer an opportunity to overlook this and if they encounter this on their job the tips may be able to provide resources on making CAPTCHA accessible.

We use CAPTCHA for students/faculty/staff to log into our system if they have forgotten their password. We are still discussing the various resources found as to which resource is valid and feasible to use within our system.

**Comment by slhenry** [comment]
[These comments apply to 20 August draft.]
"CAPTCHAs create problems for many people. " - I [mildly] think we need to be provide specific examples.
"such as: ..." -- I'm a little hesitant to include this list. Are we comfortable enough with it?
I think it would be good to get additional input beyond EOWG for this tip.

**Comment by slhenry** [comment]
for the record, minutes of EOWG discussion in 14 August telecon are here: http://www.w3.org/2015/08/14-eo-minutes.html#item01
and include: "RESOLUTION: Keep a tip on CAPTCHA, emphasize that it is inaccessible, promote the use of accessible [authentication|verification] methods"
