### ISSUE TITLE
Titles Tip - link to Easy Checks

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#161]
in Learn More, probably link to <http://www.w3.org/WAI/eval/preliminary#title> which includes useful Tips for writing titles

**Comment by iadawn** [comment]
That seems to be more about how to check that a title exists rather explain how to write good titles. Might this not run the risk of confusing readers? The most relevant part is in 'Tips' which has no link and is hidden by default.

**Comment by slhenry** [comment]
ok
