### ISSUE TITLE
Too much in tip

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#163]
From [James Green in WBS](https://www.w3.org/2002/09/wbs/35532/EOWG-17July2015/results#xwriteTp):

> Transcripts, captions, and AD.  There's a lot there, I might break it into multiple tips.

**Comment by iadawn** [comment]
In a separate email thread James indicated this was not a strong issue.

No action will be take as, while there is a lot in the tip, splitting it out would add more tips on the same topic and make them much less clear.

**Comment by James-Green** [comment]
Thanks for adding this for me, Kevin.  I'm ready to open my own issues now :)

**Comment by iadawn** [comment]
Should I worry now? ;)
