### ISSUE TITLE
Developing Examples Alignment of Rendered v. Code Snippet

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-quick-start#170]
Please ignore this if it's already been mentioned elsewhere.  But in case it hasn't been, I notice that for seven of the examples in a wider viewport "Rendered" is not horizontally aligned with "Code Snippet".  Visually this drives me nuts.  :-) 

From a quick CSS check this is because of #main .inner .html-example .code {margin-top: 1em;} 

On the other hand, in a smaller viewport this margin-top makes it so the Code Snippet doesn't bump into the Rendered version.  I'd suggest margin-top of 0 for larger viewports.

**Comment by iadawn** [comment]
Thanks... fixed.
