### ISSUE TITLE
Sneaker in code order example

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-quick-start#171]
If you all have already covered this, please ignore.  But just in case....

I love the sneaker image in the "Reflect the reading order in the code order" example.  However it seems proportionally very big compared to everything else on the page.  It would be nice if it were a little less prominent.  Maybe a duller shade of red (e.g., EOWG #993300) might de-emphasize it a bit too, though I do love bright red and I suppose all stars are anything but dull and small....

**Comment by iadawn** [comment]
I have toned this down. There may be more discussion on this one though. Thanks

**Comment by happywebdiva** [comment]
Thanks, Kevin!  No worries if I'm overruled.  Just a diva.  ;-)
