### ISSUE TITLE
'Reflect'

### ISSUE THREAD

**Issue by LydiaHarkey** [w3c/wai-quick-start#172]
Developers may misinterpret the word 'Reflect' for reading order as an awareness versus verifying the reading order

meant to place elsewhere.

**Comment by iadawn** [comment]
Verification of the reading order is more of an evaluating activity rather than a developing activity. I have tried to avoid blurring this too much.

Would you want a different word other than 'reflect' that doesn't stray too much into evaluating? Suggestions are welcomed ;)

**Comment by sharronrush** [comment]
Verification is the wrong word in this context.  And in context, in fact, it would be difficult in my opinion to think we are using "reflect" in the sense of thinking and awareness.  Strongly feel that reflect is just the word we want here.  It is clear and succinct.

**Comment by slhenry** [comment]
I agree not "verify" because that's after the fact. Reflect is OK; however, maybe we can use a clearer word, especially for non-native speakers.

How about "match"? Something along the lines of: Make the code order match the reading order.

**Comment by iadawn** [comment]
I don't overly mind 'match' but I was concerned that this is possible too exacting. Sometimes it is not as clear cut as 'match' might suggest, hence why I went for 'reflect'.

**Comment by LydiaHarkey** [comment]
This may be an option 'Ensure text order is logical' this could prompt the developer to think about reading order and if the text is in logical order.

**Comment by iadawn** [comment]
Thanks @LydiaHarkey, my only concern with your suggestion is that it may miss what the point of the tip is. The aim is really to consider how the presentation order matches (or doesn't) the DOM. One difficulty is that I think 'logically' may be too precise a term as there isn't necessarily a logic within the tip; it is much more about thinking about how people consume content. Also, sometimes there isn't much in the way of logic in the presentation, and there is no best or logical approach, just as long as this is thought about and there is some relationship.

Could I ask how strongly do you feel about this issue?

**Comment by LydiaHarkey** [comment]
I am comfortable with current wordings.Lydia 


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------
