### ISSUE TITLE
Keep content clear and concise: Additional content type suggestions

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#180]
[Keep content clear and concise](http://w3c.github.io/wai-quick-start/writing.html#keep-content-clear-and-concise)

In order to have some consistency with WCAG wording, the final bullet point in this tip now includes suggestions of considering more than just images:
"Consider using images, illustrations, video, audio, and symbols to help clarify meaning."

**Comment by metzessible** [comment]
I have some wordsmithing for one bullet, so apologize if this is not the right time and place for them:

* Avoid using overly complex words and phrases. Consider providing a glossary for terms readers may not know. 

**Change to:**
* Avoid using ***unnecessarily*** complex words and phrases. Consider providing a glossary for terms readers may not know.

**Comment by sharronrush** [comment]
+1 to Jon's suggestion

**Comment by slhenry** [comment]
+1 to Jon's suggestion

and another minor change:
"Consider providing a glossary for terms readers may not know."
-> "Consider providing a glossary for terms readers might not know."

**Comment by iadawn** [comment]
Closed following changes made. If there are still issues, please reopen.
