### ISSUE TITLE
Example in Developing - Code Order tip

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#182]
<http://w3c.github.io/wai-quick-start/developing.html#reflect-the-reading-order-in-the-code-order>

I think the text needs to be clearer. Perhaps:
* "Code order does not reflect reading order: Order matches visual presentation, but is not logical."
-> "Code order does not reflect logical reading order - image is before product name"
* "Code order reflects reading order: Product title is logically viewed first, so presented first in code."
-> "Code order reflects logical reading order - product name is before image"

I think you might need to add more code/CSS to show how the second example would be rendered visually as above -- otherwise, it doesn't have credibility.

Also, I wonder if the "..."s in the examples will be confusing?

**Comment by iadawn** [comment]
Change made ad09de0
