### ISSUE TITLE
Provide meaning for non-standard interactive elements – Strongly suggest using native elements if possible

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#183]
In the example for [Provide meaning for non-standard interactive elements](http://w3c.github.io/wai-quick-start/developing.html#provide-meaning-for-non-standard-interactive-elements) the example should at least mention that, if possible, native elements should be used.

The example should use a `button` element which ensures that the element is focusable (Currently `tabindex="0"` is used but the use should probably be explained here as well if `button` is not used.)

**Comment by nitedog** [comment]
Agree with Eric - this contradicts the "progressive enhancement" tip just above. This needs a better example where non-standard elements (eg. button) cannot be used. Maybe a span element that is an active field, for example for notifications - like "you have 55 unread emails" or "5 items in your shopping basket"?

**Comment by iadawn** [comment]
@yatil I could change this to a button. This removes the need for the `tabindex` and some of the code.

@nitedog I will have a think and see if there is a suitable alternative (and I won't quote your 'love it' comment back to you ;)). I think your two suggestions may not meet the simplicity bar, as I think they would require other elements to highlight the interactions.

**Comment by iadawn** [comment]
@nitedog, actually I wonder if it is such a problem. A button isn't designed to do the sort of thing in the example, so it is being used in a non-standard way. Just a thought.

**Comment by iadawn** [comment]
On discussion with @nitedog, agreed to look at using a menu implemented using a `<ul>` with all the appropriate ARIA and keyboard controls.

**Comment by yatil** [comment]
Hm. The menu example is quite complicated (see [tutorial on flyout menus](http://w3c.github.io/wai-tutorials/menus/flyout/)) – Indeed instead of using a button a checkbox would be more appropriate here…

As always with those examples it is a fine line to have a valuable example that is simple enough to illustrate just one point.

**Comment by iadawn** [comment]
The aim really is to provide an example that uses mark-up in a non-standard way. Agreed that this is really a checkbox, when you get down to it - that was one of my earliest concerns. Menus are handy as an example as there really is no HTML elements that are menus. I guess that is what I am looking for; something which has no analogy in HTML.

Back to the drawing board I think :)

**Comment by iadawn** [comment]
Changed example to be simple HTML of menu. Closing issue... if there are still concerns, please do reopen.
