### ISSUE TITLE
Help users avoid and correct mistakes – Example not working

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#184]
Entering the example should not result in an invalid field: 
![](https://cloud.githubusercontent.com/assets/58862/9519187/e457905c-4cbc-11e5-9ed4-5dc104fa30b3.png)

The correct code is this, I believe:

```js
\(?0[1-9]+\)?([ -]?[0-9]{4}){2}
```
(alternatively, if the amount of spaces/dashes between the blocks of numbers doesn’t matter:
```js
\(?0[1-9]+\)?([ -]*[0-9]{4}){2}
```
)

![](https://cloud.githubusercontent.com/assets/58862/9519402/ad2bd7e4-4cbe-11e5-9fb9-168c13dff15f.png)

**Comment by iadawn** [comment]
That is what I get for trusting the internet ;)

A better form may be:

> ^(\(?0[1-9]{1}\)?)?[0-9 -]*$

This would allow for mobile number and for the changing convention regarding the inclusion of parenthesis. [Australian phone number conventions](http://www.wikiwand.com/en/National_conventions_for_writing_telephone_numbers#/Australia)

**Comment by yatil** [comment]
Couldn’t you have researched easier conventions? ;-)

**Comment by iadawn** [comment]
Hmm... although that does not allow for full validation as 01123 would match as well as 04123412341234. Then again, this is not to illustrate how to write a phone number validator, but how to be forgiving in what is accepted. The back end would need to worry about stripping spaces, parenthesis, hyphens and then checking it is 10 digits long.

Easy, yes; Illustrative? don't know ;)
