### ISSUE TITLE
Provide, Provide, Provide

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#186]
When reading through the list of content at the top, there are three consecutive tips that start with provide:

* Provide text alternatives for images
* Provide transcripts and captions for multimedia
* Provide clear instructions

I don’t have particular suggestions but it would be good style to have different words there.

**Comment by sharronrush** [comment]
provide and ensure seem to be our fall back words. How about:
- Apply meaningful text alternatives to images
- Create transcripts and captions for multimedia
- Provide clear instructions

**Comment by iadawn** [comment]
What about:

> Write meaningful text alternatives to images

**Comment by sharronrush** [comment]
yep seems good to me

**Comment by iadawn** [comment]
Addressed with dcbb390

**Comment by yatil** [comment]
👍
