### ISSUE TITLE
[minor] Provide informative, unique page titles – Non-responsive example

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#187]
The example in the tip “provide informative, unique page titles” is not responsive and triggers horizontal scrolling.

Maybe [using `text-overflow: ellipsis;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) and a max-width of 100% does the trick.

![Screenshot where horizontal scrolling is triggered](https://cloud.githubusercontent.com/assets/58862/9598738/5b684e00-508e-11e5-9ae8-092cbf39bf09.png)
![screenshot scrolled to the right](https://cloud.githubusercontent.com/assets/58862/9598752/6d6cd1a2-508e-11e5-9776-9a91187d0c7d.png)

**Comment by iadawn** [comment]
Hmm... responsive SVG... something new to learn I guess.

**Comment by yatil** [comment]
Yep. Alternatively you can use `overflow: scroll; max-width:100%;` on the container element.

**Comment by iadawn** [comment]
Used your solution, Eric. However, I would like to revisit this to see if there is a more elegant way to do it.
