### ISSUE TITLE
Write meaningful text alternatives for images – Example looks like alt text visible

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#188]
In “Write meaningful text alternatives for images” I miss a note that the alternative text is embedded invisible to the document. That the alternative text is visible in the example reinforces that. Maybe add a toggle button [show/hide] alternative text. I see the need for the writer to specify the alt text but I think we shouldn’t mislead here…

**Comment by iadawn** [comment]
In this case the activity of writing does not involve creating the actual code. I think I would prefer to include a note to explain what alternative text is a little more, rather than including a toggle button.

**Comment by yatil** [comment]
Would be fine for me. Alternatively the alt text could be styled more like a post it note or (now it’s getting fancy) in a cursive font to show that this is a note that is taken in the writing process.

**Comment by iadawn** [comment]
I think that might fall foul of the style police ;)

**Comment by iadawn** [comment]
Close on change, please reopen if you think it needs more

**Comment by yatil** [comment]
Like it! :+1:

**Comment by slhenry** [comment]
I think we should re-do the example/illustration so the alt text does not look like it's part of the content. 
One idea would be to make it look like a pop-up tooltip kinda thing. &/or write:
alt="Charging phone"
I'm fine with saving this to next update -- not in Sept -- although before March 2016. :-)

**Comment by yatil** [comment]
It is part of the content that the writer needs to think about, and if they give their text to an implementer, this is important to note for them.

I suggest making the alternative text hint italic so that it looks more like a note.

I strongly, strongly, strongly think that we should not use tech jargon or even code (like `alt=""`) but use natural language, especially in non-developer tips.
