### ISSUE TITLE
About WCAG box minor edit

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#190]
remove `<abbr>` from:

```html
<p>Web Content Accessibility Guidelines (WCAG) is the international standard for
making web content more accessible to people with disabilities. The
<abbr title="Web Content Accessibility Guidelines">WCAG</abbr> requirements are
called "success criteria" (SC).</p>
```
rationale: it adds unnecessary clutter since the acronym is expanded in the previous sentence.

(sorry I couldn't find the box to make the change and do a pull request.)

**Comment by iadawn** [comment]
Sorry, you have lost me. What are you suggesting be removed?

If you wish to do a pull request of this the file can be found at: https://github.com/w3c/wai-quick-start/blob/master/source/layouts/_what_is_wcag.erb

**Comment by James-Green** [comment]
I believe Shawn is suggesting you remove the <abbr> from WCAG in the second sentence of the what-is-wcag aside since you spell it out in the previous sentence.  I would agree that it's not necessary.

**Comment by iadawn** [comment]
Ah, actually it is to remove `<abbr>` from WCAG.

The code wasn't apparent without the backticks.

**Comment by iadawn** [comment]
Removed.
