### ISSUE TITLE
Make link text meaningful

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#195]
http://w3c.github.io/wai-quick-start/writing.html#make-link-text-meaningful

includes "Indicate the document type and approximate size in the link text where relevant."

[mild] I think this is a minor point in the big scheme of things, and not worth including in these Getting Started Tips. (But I don't object to including it if others really want to. :)

**Comment by iadawn** [comment]
I don't have strong feelings about this. The tip is short, and the added advice is not unhelpful or difficult to implement, so on balance I would recommend keeping it in.

**Comment by yatil** [comment]
±0 – I think it is a nice touch and gets forgotten a lot.

**Comment by James-Green** [comment]
I think we do a good job of subtly mentioning things here and there to give people paths to think and learn more.  This suggestion improves usability and encourages writers to think in a "some information is hidden from users, I should try to expose it" way that will help them implement accessibility more successfully.

**Comment by iadawn** [comment]
This was tweaked slightly in b6e6ac8 to make it less prominent.

Closing, if the concern remains, please reopen.

**Comment by yatil** [comment]
👍
