### ISSUE TITLE
Minor thing with code order tip in Developing Tips

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-quick-start#206]
The greens of the sneaker and "add to cart" button clash a little.  If you have the time to adjust one color or the other, great.  If not, no worries.

**Comment by iadawn** [comment]
Changed to a purple... good thing I have a wide selection of trainers ;)

**Comment by happywebdiva** [comment]
Oooooo......  I LOVE purple!  My sneakers have a Liberty floral on them.
Seriously.  And I thought Liberty florals were for little old ladies.  But
then again, some might say I'm a little old lady......

**Comment by sharronrush** [comment]
love the purple too (as a fellow lol)
