### ISSUE TITLE
Provide meaning for non-standard interactive elements - Slider checkbox

### ISSUE THREAD

**Issue by melodyma** [w3c/wai-quick-start#208]
Intro paragraph includes sentence that gives examples "For example, role='slider' and aria-expanded='true'.", but not used in actual checkbox slider example. This is confusing.

**Comment by iadawn** [comment]
The aim was to try to introduce a few things to think about. So, one or two in the text, and one or two in the example. This was connected with showing the range of options, without just listing them all out, so as to encourage readers to explore further.

How strong are your concerns?

**Comment by nitedog** [comment]
I think it might actually be worthwhile to consider using the same in the text and example. You will link to further materials for those who want to learn more about other roles and attributes. The potential confusion that this creates does not seem worth the little value added.

**Comment by iadawn** [comment]
Changed the description to relate to the example to avoid introducing any confusion. If there are still concerns, please reopen this item.
