### ISSUE TITLE
"Add a comment or issue directly on Github"

### ISSUE THREAD

**Issue by davidberman** [w3c/wai-quick-start#212]
On all pages that include this object...
1. Reword this message to be clearer as to where it takes you.
2. Make this offering more apparent/usable by turning it into a button, such as the "Fork..." that follows.
3. Spell "GitHub" correctly here and elsewhere.

**Comment by iadawn** [comment]
I have made some changes to the contribute panel. If these address your concerns, please close this issue. If you have further comments, please do add them here.

**Comment by James-Green** [comment]
I like the changes.
