### ISSUE TITLE
"Learn more"

### ISSUE THREAD

**Issue by davidberman** [w3c/wai-quick-start#213]
We should consider rewording the heading for this recurring section to correct the potential misperception that "Learn more" takes you deeper into the Tips, rather than the truth which is that it takes you outside this 101 space... to "Hitting The Books" or "The Nitty Gritty" ... it needs to imply that it takes you to "the Law" and also potentially to tutorials etc on other sites.

**Comment by sharronrush** [comment]
Good point, but doesn't Learn More imply that you are learning more about the issue itself and not the approach? The suggestions provided seem too informal and other terms that occur to me - like Background and Overview seem vague.  What about Additional Resources?

**Comment by davidberman** [comment]
I like Additional Resources as it implies they are external. However how
about something friendlier akin to Nitty Gritty. Or perhaps the link to the
SC deserves its own phrase that implies it is the official bottom line?

<David Berman berman@davidberman.com

**Comment by sharronrush** [comment]
Just have to be careful about informal terms like Nitty Gritty or Full
Scoop or like that due to the need for translation. That's one reason we
often sound like such stuffed shirts :)

**Comment by AndrewArch** [comment]
Additional Resources sounds good - just need clear headings for what they are :)

**Comment by James-Green** [comment]
I like Additional Resources, though Learn More worked for me too.  I agree that we should not get too informal or use idioms.

**Comment by nitedog** [comment]
How about "Related Resources" or "Related Guidance"? I think the word "related" may help underline that it is not always a 1:1 mapping to the resources provided - that is, they are not always in addition.

**Comment by sharronrush** [comment]
Related resources seems good.

**Comment by gheake-1** [comment]
I think Related resources is more to the point. But I could also live with Additional Resources. I also agree we should not go the informal route.

**Comment by vmmiller** [comment]
+1 Related resources

**Comment by James-Green** [comment]
+1 Related Resources

**Comment by LydiaHarkey** [comment]
Related Resources may work as it indicates there are other resources related to the topic whereas Additional Resource may be construe as 'in addition to the resources provided visit x page for for information'

**Comment by AndrewArch** [comment]
yes - Related Resources is good as they are all W3C/WAI resources

**Comment by iadawn** [comment]
Changed with f87fa62

Closed based on resolution in [EO meeting of 11 Sep](http://www.w3.org/2015/09/11-eo-minutes.html)

**Comment by slhenry** [comment]
About the change from Learn More to -> Related Resources:
In most cases, the tip text briefly introduces the issue, but is not sufficient information for people to implement the tip effectively. Usually they will need to follow at least some of the links to Learn More about the tip. Because of this, I'm hesitant to change "Learn More" to "Related Resources".  "Learn More" is active and imperative; whereas, "Related Resources" is passive and does not say 'follow these links'. [medium-strong]

**Comment by nitedog** [comment]
1. To me "learn more" is quite boring (passive) but I'm not stuck on wording.
2. The reason for "related" is because the resources are not always directly on the point that was briefly introduced - I think something less direct is important.
3. How about "find out more" or such? Just tossing an idea...

**Comment by yatil** [comment]
I still like “related resources”, it is to the point and also consistent with the tutorials, for example: http://w3c.github.io/wai-tutorials/menus/#related

**Comment by slhenry** [comment]
In 18 Sept telecon, I said: "I appreciate the consideration of my POV but it is not high priority for me, I can accept the resolution from last week." <http://www.w3.org/2015/09/18-eo-minutes.html#item02>

But looking at the page again for other things, it keeps still bugging me.  :-(

Another idea:
<blockquote>For more information:</blockquote>
* it encourages people to follow links
* it doesn't say these are related or not related or directly on point or tangential
* It addresses David's first point that these are not more tips
* looking over the minutes, I see Kevin put that in IRC but it got lost and not discussed :(

**Comment by James-Green** [comment]
i like it.

**Comment by James-Green** [comment]
Since the survey asked us to comment on this issue and other parts of this (more info) section are being discussed in #215 I'm duplicating what I suggested over there here:
> For more information...
> * Related WCAG Requirement(s)
>    * ink to quick ref (link to understanding)
>    * another link to quick ref (link to understanding)
> * ...

**Comment by nitedog** [comment]
I like "For more information". It sounds active to me and non-binding, as @slhenry explains.

**Comment by slhenry** [comment]
or even more active:
For more information, see:
* WCAG...

**Comment by AndrewArch** [comment]
"For more information" works for me - lets keep it at that

**Comment by iadawn** [comment]
Changed to 'For more information', and closing. Please reopen if there are still concerns.

**Comment by sharronrush** [comment]
Yes, "For More Information" is great with me.

**Comment by bakkenb** [comment]
I agree as well.

**Comment by yatil** [comment]
👍

**Comment by davidberman** [comment]
I agree.

**Comment by LydiaHarkey** [comment]
I agree 'For more information' is much friendlier.

**Comment by gheake-1** [comment]
I was about the convert to Learn More but For more information is more on target with what we are trying to accomplish.

**Comment by vmmiller** [comment]
I think "For more information" works.

**Comment by happywebdiva** [comment]
I'm fine with "For more information" too.

**Comment by hkramer** [comment]
I concur - go with "For more information"

**Comment by metzessible** [comment]
I agree with "For more information," as well.
