### ISSUE TITLE
Learn more links: order and what is being linked to

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#214]
Topic raised in [EO meeting on 4 Sep](http://www.w3.org/2015/09/04-eo-minutes.html).

A few concerns were raised:

* The order of the links may not be suitable for the target novice audience
* The first link says 'Requirement' but does not go to the actual requirement
* Order of links may not introduce novice readers in a reasonable way

**Comment by AndrewArch** [comment]
Proposal to start the discussion (include as available/provided) as these are tips for people relatively new to thinking about accessibility:
1. Rationale (link to Understanding)
2. User Stories (link to 'how people ...'')
3. How To (link to Easy Checks)
4. Tutorial (link to appropriate tutorial section)
5. WCAG Requirement (link to TR)
6. Solutions **OR** Techniques (link to QuickRef)
7. Support Tools (??)

**Comment by iadawn** [comment]
Related tip raised by @James-Green #215

**Comment by sharronrush** [comment]
+1 to Rationale, good choice. Overall I like all except don't think we should include both #5 and #6 - Quick ref is sufficient in my opinion.

**Comment by nitedog** [comment]
Remember that people get really frustrated when we present all the background before the actual "tell me what to do". For example, people will likely read the user stories only once or twice, and after that hopefully want to go to the QuickRef or such - having to wade through all the links each time was often expressed as an issue in the past. I suggest linking to QuickRef first ("tell me what to do"), and then the explanations - for those who want - directly below. See my suggestion in #215

**Comment by gheake-1** [comment]
i would agree that 5 & 6 should not be included. The link tile Quick Reference  would be appropriate. I would further agree linking to QuickRef first and then explanations, is the best route to take. I think most people that made this far, want the steps, as soon as possible.

**Comment by LydiaHarkey** [comment]
Even though Quick Ref may be sufficient I think including #5 is beneficial for someone who needs to review or share the WCAG requirements. This information provided may used by person who is not doing the work but need to provide information for others i.e., management, compliance report, etc.

**Comment by sharronrush** [comment]
Please clarify. I am not sure what you mean. Why could "management,
compliance report" not use QuickRef effectively, thereby rendering
unnecessary a link to the specification itself?

**Comment by LydiaHarkey** [comment]
When writinga report to or for management having  a reference to wcag 2.0 provides support in particular meeting a compliance criteria and also provides support when being asked 'why is this important?' Being able to refer to wcag 2.0 in a report or discussion often sways the opinions of others and brings understanding of the importance of accessibility. 


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by nitedog** [comment]
The QuickRef includes the WCAG Success Criteria (plus the Techniques and Understanding). What does it not provide that you need from the actual TR document?
Also, I'm a little concerned about the use-case that you are describing, which seems to imply using these start-up tips as a checklist for management, which is not really what we would want IMO.

**Comment by sharronrush** [comment]
Understood, but why can they not get exactly that from the Quick Ref link?

**Comment by iadawn** [comment]
Addressed with 63df125

Closed based on resolution in [EO meeting of 11 Sep](http://www.w3.org/2015/09/11-eo-minutes.html)
