### ISSUE TITLE
Content, order, and naming within Learn More section.

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#215]
Based on our discussion today, I think we need to think through the learn more section and decide on what goes there, as well as the order and naming we use.  This is related to issue I'd like to collect feedback separately in the three areas:

**1. Content:** *What should go in this section and why?* Currently it contains links to relevant (in no specific order):
* Tutorial(s)
* Techniques and Failures(s)
* Understanding(s)
* User Story(s)
* Support Tools(s)

**2. Order:** *In what order would you present them and why?* The current order is:
* Techniques & Failures
* Tutorial
* Understanding
* User Story
* Support Tools

**3. Naming:** *What names would you assign to the items in the list you mention above?*  Currently:
* WCAG Requirement (Techniques and Failures Document)
* Tutorial (Tutorial)
* Background (Understanding Document)
* User Story (User Story)
* Support Tools (List of related tools)

**Comment by James-Green** [comment]
1. I think we need to add a link to the actual source WCAG 2.0 requirement - it's the basis for everything and I thinks users would expect a direct link.

2. Understanding, Tutorial, Techniques & Failures, User Story, Support Tools, WCAG Requirement.

3. Background & Intent, Tutorial, Techniques & Failures, User Story, Support Tools, WCAG Requirement.

**Comment by sharronrush** [comment]
Not sure I agree with the need to link to the requirement and don't think we should link to both that and to the QuickRef. If I had to choose, the QuickRef is so much more flexible and user friendly that would be my choice. "users would expect a direct link" might depend on the type of user. Many in my experince just want a translation and a directive - just tell me what to do. Those who really want to find the Holy Grail of the requirement itself can easily get there through the QuickRef

**Comment by nitedog** [comment]
I agree with @sharronrush about reducing what we link to. I do not think we should link to Techniques, and maybe not even to Understanding - these are prominently linked from the QuickRef, especially in the [update in development](https://w3c.github.io/wai-wcag-quickref/). I think the QuickRef should be the first links, to address the "tell me what to do". Then the tutorials, easy checks, and user stories (in that order), when they are relevant. For example:

Use Headings to Convey Meaning and Structure
[blurb of text]
Related Resources
* WCAG Requirements
** SC 2.4.6 Headings and Labels (links to QuickRef)
** ...
* Tutorial
** Designing Page Headings (links to http://www.w3.org/WAI/tutorials/page-structure/headings/)
* Easy Check
** Checking Page Headings (links to http://www.w3.org/WAI/eval/preliminary#headings)
* User Story
** Ms Laitinen uses headings to navigate (links to http://www.w3.org/WAI/intro/people-use-web/stories#accountant)

**Comment by iadawn** [comment]
Broadly agree with @nitedog, although I would suggest rather than 'WCAG Requirements' the term 'Related Requirements' be used. This avoids putting WCAG everywhere, and allows for referring to SC where there isn't an absolute one-to-one relationship between the tip and the requirement, for example, [Create designs for different viewport sizes](http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes).

Also, I would still include a link to the Understanding document somehow. Even if it is as:

* Related Requirements
  * [2.4.6 Headings and Labels](http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-descriptive) ([Understanding 2.4.6](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html))

**Comment by James-Green** [comment]
All right, you've changed my mind.  +1 to @iadawn's last suggestion.

**Comment by LydiaHarkey** [comment]
+1 to @iadawn's last suggestion

**Comment by iadawn** [comment]
Addressed with 63df125

Closed based on resolution in [EO meeting of 11 Sep](http://www.w3.org/2015/09/11-eo-minutes.html)

**Comment by slhenry** [comment]
Sorry, I disagree. [medium-strong] It should be "WCAG requirement".
It should be very clear where those links are going -- to WCAG requirements. "Related requirement" could go anywhere. And we want to reinforce "WCAG".
For those few cases where the tip provides best practice not directly required by WCAG, it should say "Related WCAG requirement.

**Comment by slhenry** [comment]
Most of the tips are requirements in WCAG. My suggestion above was for the heading to be "WCAG Requirement" for those -- and only "Related WCAG Requirement" when the tip has more than is a WCAG requirement.
/me dislikes the Related redundancy in:
<blockquote>
Related resources
* Related WCAG Requirement
</blockquote>

**Comment by James-Green** [comment]
If we go with your last suggestion of "For more information..." seen in #213 then we don't have the redundancy, so +1 to that :)

My comments and eventual agreement above were with linking to the quick ref instead of the TR and additionally linking to the understanding doc is even better in my opinion.  

Regarding the inclusion or exclusion of "related" in the WCAG link, I'll argue that if the tip is a 1:1 match to a requirement, there would obviously only be one relevant WCAG requirement for us to link to, but the relationship between the tip and the requirement is still a relationship, they are not the same.  The tip is a tip that paraphrases and expands on the requirement.  That said, I personally see nothing wrong or misleading with always using "Related" regardless of the relationship, with the added bonus of no need for any exceptions or logic as they could all say this:

> For more information...
> * Related WCAG Requirement(s)
>    * ink to quick ref (link to understanding)
>    * another link to quick ref (link to understanding)
> * ...

**Comment by nitedog** [comment]
I prefer the "related" qualifier here but can live without it, as long as we have a section title that clearly communicates that the resources linked are not all 1:1 matches - I think this is an important point, and the combination of "Learn More [...] WCAG Requirement" did not work for me. "For more information" could work better.

**Comment by slhenry** [comment]
<epiphany at 5:00am Saturday morning>
/me really needs to get better at letting work go on weekends! :(

Now that all WCAG links are in one section (and the introduction relates "WCAG" to "requirements"), how about just . . . "WCAG" -- without "Related" or "Requirements" ?!?

<blockquote>
For more information:
<ul>
<li>WCAG:
<ul>
<li>1.1.1. Lorem (Understanding 1.1.1)</li>
<li>1.1.2. Ipsum (Understanding 1.1.1)</li>
</ul>
</li>
<li>...</li>
</ul>
</blockquote>

**Comment by vmmiller** [comment]
I think that would work (just WCAG)

**Comment by nitedog** [comment]
Yes, I agree that this could work. Also the explanation in the "About WCAG" is a good idea - I think part of the issue is that we wanted to differentiate these links as the formal "requirements" (whereas the tips are not requirements), but this suggested new approach (also with the new text of the intro paragraph) works for me as well.

**Comment by iadawn** [comment]
Changed from 'Related WCAG requirment' to 'WCAG'

**Comment by slhenry** [comment]
:-)

**Comment by davidberman** [comment]
Not sure if the following is epiphany-worthy: Perhaps the distinction we need to clarify for our readers beyond which WCAG SC it supports, is whether the tip is a documented WCAG technique (as well as reinforcing that there are often many valid techniques to fulfill a requirement, and so the tip itself is not itself something they must do when there are alternatives that would also result in compliance with the SC to which it traces).
