### ISSUE TITLE
VoiceOver wraps out of modal window

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#216]
Tip: [Use headings to convey meaning and structure](http://w3c.github.io/wai-quick-start/writing.html#use-headings-to-convey-meaning-and-structure)

Noted by @James-Green in [WBS survey of 21 August](https://www.w3.org/2002/09/wbs/35532/EOWG-21Aug2015/results#xq3)

**Comment by iadawn** [comment]
I am struggling a bit with this one. I have tested with JAWS and it happily reads beyond the limits of the modal dialog. I have seen a couple of solutions, but they put the modal content at the bottom of the DOM and hide the rest of the content from the screen reader. I don't think that this is a good solution as it will then function poorly where JS is unavailable.

**Comment by nitedog** [comment]
Will any modal work at all without JS? Seems good to have it at the end, with a link to it, in case JS is not activated (then the user is taken to that place in the document). If JS is activated then the content is tossed around wherever it is needed. No? What am I missing?

**Comment by iadawn** [comment]
The modal won't work without JS (and I doubt that it would be possible without JS), however, the way I have written it, if there is no JS, then the content just appears inline beside the link. It does add much more content there, but there is not much that can be done when JS is gone. This is progressive enhancement in action :)

**Comment by sharronrush** [comment]
Kevin! PE in action, you are a true action hero. Good on ya!

**Comment by nitedog** [comment]
I think using a link to go to the additional content that is on the same page, is just as well progressive enhancement.

**Comment by iadawn** [comment]
It does use a link to go to the additional content, it just doesn't put all the additional content at the bottom of the page. There are arguments for and against both positions; my general preference is to maintain a coherent flow of content. However, positioning it all at the bottom of the page may be the only way to do it... just quite difficult to achieve in the current build, as the pop-up content needs to be outside of the main body of content.

**Comment by yatil** [comment]
Imho this is a screen reader bug. If we need to solve this for screen readers, the dialog could be cloned to the end of the document and then doing the aria-hidden trick that kevin describes above.

**Comment by iadawn** [comment]
I have been experiementing with a coulpe of other accessible modal windows and I am finding the same problem. The only reason VO (and I am guessing JAWS as it was exhibiting the same behaviour when I checked) stops reading, is when there is no further content on the page. So what has to happen is all the modal windows are collected at the bottom of the page and they are all set to `aria-hidden=true` until they are needed. Also, when the dialog is opened, all other content has to be set to `aria-hidden=true`.

This is a bit of a faff and it would be nice if screen readers confined reading to within a `role='dialog'` element. Not 100% if this would be functioning as intended, but it would make like a whole lot easier.

**Comment by iadawn** [comment]
I have had a good look at the modal code and made some serious improvements to it. It is a nice example of progressive enhancement, if I do say so myself. One thing that it does do is it pulls out the modal container and moves it to the bottom of the document. This prevents the falling off the bottom that VoiceOver does. It does, however, completely break my styling of the example, so I will now need to fix that.
