### ISSUE TITLE
Showing current link in nav to screenreader users

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#218]
Topic #211 got me thinking - I think we should definitely give a second indicator to the nav list that is clearly visible, but what about helping screen reader users a bit:  

Should we indicate that the current link (which isn't a link) is the currently selected one?  My favorite method right now is to use aria-describedby on the "this page" item in the nav menu so the words "current page" are appended to the li.

I know this isn't specifically required by WCAG but would improve usability.

[The Accessible Current Page Link Conundrum] (http://www.heydonworks.com/article/the-accessible-current-page-link-conundrum) covers the topic and possible solutions pretty well.

**Comment by iadawn** [comment]
Thanks for the link, interesting piece. I am disinclined to link to the same document, this matches the approach taken within the primary navigation.

On that basis, aria-describedby may not be the best solution as it may not be communicated to the user ([found some information](http://www.mit.edu/~rjc/aria/describedby.html) but not checked with everything). However, a simple bit of hidden text may be more useful in this case?

**Comment by iadawn** [comment]
Added in off screen text to include this information. Closing issue, if this needs more attention, please feel free to reopen.

**Comment by James-Green** [comment]
that should do it :)  thanks.
