### ISSUE TITLE
A progressive enhancement approach will help ensure that core functionality and content is available regardless of technology being used.

### ISSUE THREAD

**Issue by davidberman** [w3c/wai-quick-start#222]
Eliminate passive voice (arguably a Level AAA best practice for us to model to others!): 
Example: reword sentences like this one: "A progressive enhancement approach will help ensure that core functionality and content is available regardless of technology being used." to eliminate use of the passive voice. If we are in agreement on this, I'd recommend someone sweep all the tips for passive voice, once all the substantive meaning has been pinned down.

**Comment by iadawn** [comment]
I have hopefully addressed this one. Reviewing with passive voice in mind would be helpful.

**Comment by iadawn** [comment]
Closing.

If the concerns still exist, please reopen.
