### ISSUE TITLE
Overly wordy Learn More description

### ISSUE THREAD

**Issue by davidberman** [w3c/wai-quick-start#223]
Eliminate wordiness: 

Example:
Change all this:
"These tips are important points to consider when developing accessible websites, but there is always more to learn. The following..."
to simply:
"Learn more: These..

**Comment by James-Green** [comment]
+1

**Comment by iadawn** [comment]
Shortened the introductory sentence but retained something to convey the message that these tips are just the beginning.

**Comment by iadawn** [comment]
Closing issue, if there are still concerns, please do reopen.

**Comment by slhenry** [comment]
Commenting on "These tips are only a part of web accessibility. The following resources will help you learn more about why accessibility is important, and what guidelines exist to help support people with disabilities accessing the web."

First sentence doesn't quite say what's needed. Maybe something like:
"These tips are only some things you need to consider for web accessibility."

"exist" is unnecessarily formal. also, can get rid of "will" and "more about". also, "accessing" is too close to "accessibility" and doesn't address interaction. also. "help support" has negative connotations. How about:
"The following resources help you learn why accessibility is important, and about guidelines for making the web more accessible to people with disabilities."

**Comment by iadawn** [comment]
Included suggested changes, with minor modification; removed 'only' from first sentence.

Closing.

**Comment by slhenry** [comment]
[strong]
I think it *needs* "only" or something to say that these tips are just a few things you need to do, but there is more that you need to do. I think we used to have a whole sentence or phrase saying that. I don't think it needs a whole sentence, but it does need "only". Could be better as:

"These tips are only some of the things that you need to consider for web accessibility."

**Comment by iadawn** [comment]
Changing to

> These tips are a few things you need to consider for web accessibility

I feel that 'only some' is a little pleonastic.

**Comment by slhenry** [comment]
OK, I'm not set on "only", but still needs to be more clear there are more. Suggest:

These tips are a few of the things you need to consider for web accessibility

**Comment by iadawn** [comment]
Change made. Closing.

**Comment by davidberman** [comment]
I am pleased with how this evolved. We'll stay on the lookout for similar situations elsewhere.
