### ISSUE TITLE
Chevrons on main nav are one row too low for all quick tips

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#224]
![screen shot 2015-09-09 at 1 47 15 pm](https://cloud.githubusercontent.com/assets/13589074/9771065/424dd9dc-56f9-11e5-9827-47a7e6e48959.png)

**Comment by sharronrush** [comment]
good catch, James. I did not even see that.

**Comment by iadawn** [comment]
Going to close this as it is a problem that is evident throughout the WAI site for Chrome. Anna Belle noted it to me and is going to raise it to wai-eo-editors. Thanks.

**Comment by James-Green** [comment]
ok.  FYI I saw the problem on Chrome and Safari for Mac, but it looks fine in Firefox.
