### ISSUE TITLE
Need space between example and Learn More Link on Designing...

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#225]
![screen shot 2015-09-09 at 1 50 05 pm](https://cloud.githubusercontent.com/assets/13589074/9771133/bd2bd9d8-56f9-11e5-9887-b545f8f4b607.png)

**Comment by iadawn** [comment]
@James-Green, what browser and platform are you using? I will check with the usual suspects on Mac.

**Comment by James-Green** [comment]
Safari 7.1 OSX 10.9.5.  It was only that one spot, the other examples/headings have proper space between them.

**Comment by iadawn** [comment]
Didn't find it in Safari 8 until I zoomed out, then I could find it in Firefox. Should hopefully be fixed now.

If the problem persists, please reopen.
