### ISSUE TITLE
What is “pressing interaction”?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#229]
http://w3c.github.io/wai-quick-start/developing.html#provide-meaning-for-non-standard-interactive-elements

As a non-native Speaker, I haven’t heard that phrase. I would propose using “keyboard interaction” or “how the widget reacts when using the keyboard” or something similar.

**Comment by James-Green** [comment]
The phrase wasn't familiar to me either and I suggested an edit in #238 to help clarify.  Maybe say "button press interaction" instead of "pressing interaction"

**Comment by iadawn** [comment]
Changes made based on suggestions.

Please reopen if the concern persists.

**Comment by yatil** [comment]
Much better, well done! 👍

**Comment by James-Green** [comment]
👍
