### ISSUE TITLE
Learn more about accessibility links - WCAG

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#23]
For most of the Tips pages, I think we should include a link to WCAG info -- either <http://www.w3.org/WAI/intro/wcag.php> or <http://www.w3.org/WAI/WCAG20/glance/> or both.

**Comment by iadawn** [comment]
Not averse to this although I was purposefully avoiding linking too closely to WCAG. I think the links that are in the Learn More tip will eventually connect people with WCAG, and there are/will be specific links to various Understanding pages throughout. What value do you feel readers would gain from dropping into these resources?

**Comment by iadawn** [comment]
This is effectively covered by the inclusion of the 'What is WCAG' panel (09d23365e82a5656469e4d2ebba15ff3782dff2b).
