### ISSUE TITLE
Menu button hover/focus very subtle

### ISSUE THREAD

**Issue by yatil** [w3c/wai-quick-start#230]
http://w3c.github.io/wai-quick-start/developing.html#ensure-that-all-interactive-elements-are-keyboard-accessible

It is hard to see if one has reached the button with the keyboard when I want to try it out. I suggest using underline on :hover/:focus to make the state clear.

**Comment by iadawn** [comment]
Have added underline and darkened a little.

**Comment by yatil** [comment]
👍
