### ISSUE TITLE
Introductory paragraph to "Writing" Quick Tips

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-quick-start#231]
On the "Writing" Quick Tips page (http://w3c.github.io/wai-quick-start/writing.html ), we have a more more lengthy introduction with two additional (last) sentences (see below) which could probably be added to the other pages (Design, Developing).

Current text:
"This page helps you get started writing web content that is more accessible to people with disabilities. These tips introduce some basic accessibility considerations. Each tip includes links to related WCAG requirements and resources to help you understand and implement the tip."

My question is:  
- should we remove it from "Writing" or
- should we add it to all the others (Design, Developing) 

Rationale:  
- Consistency across resources
- One group of users may not necessarily visit the other pages so they are helpful as introductory information

**Comment by iadawn** [comment]
Closing. The introduction text for Designing, Writing, and Developing have been modified in 61fde42.

If there are still concerns regarding this issue, please reopen.
