### ISSUE TITLE
tabbing feedback disappears after landing on icons

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-quick-start#234]
takes a few tabs once landing on icons to move forward

**Comment by iadawn** [comment]
Noted, I think this may be a feature of SVG. I will look into it and sort it out.

**Comment by iadawn** [comment]
Actually, was a feature of the modal windows, which was adding/removing focus to all nodes. Firefox dealt well with my stupidity, but Chrome was a bit strict.

Should be fixed now.
