### ISSUE TITLE
Tips for Developing - Change user's to users'

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#235]

**Comment by iadawn** [comment]
I am assuming this is in the tip title:

> Write code that adapts to user's technology

I think it should be "user's" as it refers to the technology (singular) that belongs to the user (singular). Although I guess there is potential ambiguity, as the definite article is not included.

> Write code that adapts to the user's technology

**Comment by James-Green** [comment]
I just felt the ambiguity would leave a reader to think we made an unintentional typo.  Adding a "the" as you did works great for me too.

**Comment by iadawn** [comment]
Added in 'the'.
