### ISSUE TITLE
Tips for Developing - Change alt='' to alt=""

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#236]

**Comment by iadawn** [comment]
Could I ask why? As single-quotes are acceptable in the specification.

**Comment by James-Green** [comment]
To prevent confusion as it's far more common to see alt="" and we use alt="" in our images tutorial as well as H67.

**Comment by iadawn** [comment]
Don't know about the commonality of double-quotes over single-quotes. I see both relatively regularly. The latter argument would sway me though ;)

**Comment by James-Green** [comment]
keep keeping me honest! :)

**Comment by iadawn** [comment]
Applied double-quotes consistently throughout resource.

**Comment by slhenry** [comment]
ftr, I also preferred double quotes, and had commented on that elsewhere (but maybe not on record)
;-)

**Comment by slhenry** [comment]
[minor]
looks like it still needs to be updated in some of the examples, e.g.,
http://w3c.github.io/wai-quick-start/writing.html#write-meaningful-text-alternatives-for-images
http://w3c.github.io/wai-quick-start/designing.html#provide-alternative-text-for-images

**Comment by iadawn** [comment]
Fixed and closed
