### ISSUE TITLE
Tips for Developing - enhance font size sentence...

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#237]
To enhance and clarify the "Avoid clipping and horizontal scrolling when font size is increased." sentence, I suggest changing it to "**Prevent** clipping and horizontal scrolling when font size is increased **(to at least 200%)**".

Not strong on the 200% or the exact wording of that part, but I think Prevent is a much better word than Avoid.  It implies necessary action on the developer's part.

**Comment by iadawn** [comment]
The slight challenge I have with this is that there is nothing which requires that horizontal scrolling should be prevented. I know it should be avoided at all costs, but 'prevent' suggests something much stronger here than we do elsewhere.

What about something like:

> When font size is increased by at least 200%, avoid horizontal scrolling and prevent any clipping of content.

**Comment by James-Green** [comment]
love it.

**Comment by sharronrush** [comment]
+1 to "Prevent"

**Comment by iadawn** [comment]
Closing following accepted change.
