### ISSUE TITLE
Tips for Developing - remove a couple commas

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#239]
I suggest changing 

"Think about keyboard access, especially when developing interactive elements, such as menus, mouseover ... into the navigation order, when it is being used for interaction..." 

to the following (:x: icons represent removed commas)

"Think about keyboard access, especially when developing interactive elements:x: such as menus, mouseover ... into the navigation order :x:when it is being used for interaction..."

**Comment by iadawn** [comment]
The first comma is used to split out the examples from the main sentence. This is a common style approach in the resource so I have left that in.

Second one, agreed unnecessary so has been removed.
