### ISSUE TITLE
Reflect the reading order in the code order

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-quick-start#240]
Really minor comments:

1) in the code snippet of this example, can the text be entered in full to reflect the example (as done in the example of "Use mark-up to convey meaning and structure":

Code snippet example:

<h3>Space trainers</h3>
<img src="images/trainer-cc785555.png" alt="...">
<p>Space...</p>
<a href="...">Add to cart</a>

Instead of <p>Space...</p> can the full text be entered which is:
<p>Space trainer for a classic and stylish look.</p>

Rationale:
- consistency
- ease of understanding

2)  Should the alt text in this case be empty or should it have some description?  Just to ensure that - if it is decorative, that's fine, it's empty.  But if it isn't decorative, then, probably some alt text should be entered to produce a complete example.

**Comment by nitedog** [comment]
I think the idea was to put "..." instead of the text (also the alt text) to save space, and to focus on the order in which the elements appear (image before heading vs after heading). Is this too confusing?

**Comment by iadawn** [comment]
9344e59 Introduced two links to allow the user to easily view the full source code.

If there are still concerns, please reopen issue.
