### ISSUE TITLE
An example for page language?

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-quick-start#244]
This is a minor suggestion. As a lazy developer, I'd like to see an example for the "Identify page language and language changes" section that I can use either as a double check to be sure I'm understanding as I skim through the page or to copy/past/adapt.  I know an example would be minuscule -- only about 16 chars -- but, hey, I'm not the only lazy developer out there. If you've already thought about this and rejected it, no worries.  Us lazy developers can cope....

**Comment by iadawn** [comment]
Added for all lazy developers of english language sites ;)
