### ISSUE TITLE
Suggested rewrite of first few sentences of Overview

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-quick-start#245]
(1) I just registered that the first sentence of the overview page has an exclamation point.  ("Get started with web accessibility, even if you only know little about it!")  While this document isn't nearly as formal as a lot of other ones from the W3C, IMO it's still formal in the sense that it's not informal -- and grammarians discourage exclamation points except for informal prose. In general, I don't see the point of this sentence and would suggest striking it altogether.  But if you keep it, please delete the exclamation point.

(2) I like it that the overview text is super short.

(3) The first comma in the second sentence (after "considerations") isn't needed.

(4) Might v. may.  Normally I wouldn't bring this up, but as long as I'm pontificating on these few sentences, I'd suggest using may in the last one.

Here's a possible rewrite (with some preposition changes too, to make the flow a little smoother).  

"These tips introduce some basic considerations and links for further guidance to help you learn about and implement web accessibility for people with disabilities. Depending on your role, you may find useful tips in more than one category."

Please feel free to ignore this feedback (except about the exclamation point).  :-)

**Comment by bakkenb** [comment]
I agree with the exclamation point. I think that entire first sentence does not fit with the opening paragraph. To me it reads more like a title for the paragraph or a pull quote. 

I like the rewording that is suggested by <b> @happywebdiva </b>.

**Comment by nitedog** [comment]
I agree with the rewording and getting rid of the exclamation mark, as suggested by @happywebdiva .

Regarding the first sentence - I was hoping it would be an engaging opener. The sentence should also communicate that this resource, unlike most other WAI resources, is suitable for people new to accessibility. These are our target audience and I think we need to try and address them as directly as possible. Maybe there could be alternate approaches to this, though.

**Comment by iadawn** [comment]
Incorporate most changes. Leaving open for any discussion on leading sentence.

**Comment by iadawn** [comment]
First sentence has been shortened to:

> Get started with accessibility

Aim is to try to have something a bit more informal, that (seriously) summarises the content, and that will appeal to the right audience.

Topic will be discussed in EO so closing this for the moment.
