### ISSUE TITLE
Tips on Developing for Web Accessibility - Thorough Review

### ISSUE THREAD

**Issue by gheake-1** [w3c/wai-quick-start#246]
I believe the Tips on Developing for Web Accessibility provides a good balance to a wide audience between the new developer with no knowledge of accessibility and the "older" developer looking for information on the this thing they are calling accessibility. That might be overstating it a bit but although many developers and the stakeholders responsible for them do not understand what it takes nor what to do.

I think the tips are solid start not only for imparting knowledge of what to do, but shines some light on the benefit in incorporating the tips and similar accessibility information into the development workflow and we can only hope into their best practices for development.

The structure well laid out and the information is present in a simple concise manner.

Well done..

**Comment by iadawn** [comment]
Thank you :)
