### ISSUE TITLE
Consider including a Design tip about images

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#25]
Raised by Vicki in [Survey on 3 Jun 2015](https://www.w3.org/2002/09/wbs/35532/EOWGTipsJune1/results#xdesign)

**Comment by slhenry** [comment]
Vicki's wording from survey:
"Add: a pointer to the images tutorial
Rationale: Images are so much part of design (thumbnails on portals to link to further information, images with text, images to perk up designs, logos etc). I think it would be important to have a link to further guidance on images."
E-mail thread: <https://lists.w3.org/Archives/Public/wai-eo-editors/2015Jun/0044.html>

**Comment by slhenry** [comment]
page this relates to: Tips on Designing for Web Accessibility http://w3c.github.io/wai-quick-start/designing.html

Vicki's comment in survey:
"Add: a pointer to the images tutorial
Rationale: Images are so much part of design (thumbnails on portals to link to further information, images with text, images to perk up designs, logos etc). I think it would be important to have a link to further guidance on images."

e-mail thread: https://lists.w3.org/Archives/Public/wai-eo-editors/2015Jun/0044.html

**Comment by slhenry** [comment]
(I note that Vicki suggested adding a pointer to the Images Tutorials, but not necessarily adding a design tip.)
I think we can add a specific pointer to the Images Tutorial in the Learn More section. Right now it points to the main Tutorials page, but do any of the other tutorials apply to Designing? Maybe we point just to the Images Tutorial and add that it tells you what alt to provide for images...
Having said that, I think we *might* want to include a tip for providing alt for the images. In many cases (when the designer is providing the images), isn't the designer the best person to provide the alt? Don't they know better than others what the image is suppose to convey for the content, and thus they should give the alt text to the coder? (Although they might be inclined to do lengthy alt for decorative images that should be null, and so we might want to warn against that? :-)

**Comment by iadawn** [comment]
Providing alternative text is including with the Writing tips. It wouldn't normally fall within designing activities and so I decided not to include it here.

I appreciate the perspective that the designer may be providing the alternative text, but I can't say that I have ever experienced that. It is much more likely to be a content manager.

**Comment by vmmiller** [comment]
Shawn - I very much like the approach in the second part of the message where you suggest including a tip for providing alt for images and which would provide guidance to designers.  I'd like to propose the following text:

Heading proposed:
"Ensure images contain a text alternative"
or
"Provide a text alternative for images"

Images must have text alternatives that describe the information or function represented by the images. For example, an image might be used in a functional way, such as an icon to link to another page or as a decorative feature to enhance the design of a page.  It is important to consider the purpose of each image and to assign a text alternative accordingly.

Learn More:

WCAG Requirement:
Background:
Tutorial:

**Comment by melodyma** [comment]
I ran an accessibility training session with designers and content writers in the room recently and the most frequent questions were: 1) Does colour contrast ratios apply for text over images with varying gradients and shades; 2) How do I use alt text properly?

**Comment by iadawn** [comment]
Do you think question 1. would merit an example or comment?
Did question 2. come from designers as well as content writers?

**Comment by vmmiller** [comment]
Kevin - I've had the comment from both designers and content writers, but more from designers.

**Comment by bakkenb** [comment]
I would like to see a tip about images and alternative text in the design section.

**Comment by yatil** [comment]
[medium-strong] I don’t feel alt text to be something (visual) designers need to be concerned about. I would instead have an example formatted as a figure or something like that. How to handle text that is laid out over images and/or gradients is a different matter and might be very interesting addition to the [Provide sufficient contrast between colors](http://w3c.github.io/wai-quick-start/designing.html#provide-sufficient-contrast-between-colors) section of the tutorial.

**Comment by iadawn** [comment]
## Summary of feedback
* Yes
  * VM - 'Ensure images contain a text alternative' or 'Provide a text alternative for images'
    'Images must have text alternatives that describe the information or function represented by the images. For example, an image might be used in a functional way, such as an icon to link to another page or as a decorative feature to enhance the design of a page. It is important to consider the purpose of each image and to assign a text alternative accordingly.'
  * SLH - shouldn't designers be the ones to know about what purposes images serve?
  * BB
  
* No
  * EE+++
    Suggest addition on how to handle text laid over images and/or gradients

**Comment by yatil** [comment]
Is not feeling strongly anymore. I still think it is not _needed_ but I’m happy with whatever the group thinks is OK.

**Comment by iadawn** [comment]
[EO Meeting on 3rd July 2015](http://www.w3.org/2015/07/03-eo-minutes.html#item03) resolved to explore such a tip.
