### ISSUE TITLE
Add tip concerning consistent element naming conventions

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#26]
From @sharronrush:

> Things like using the same name in the code as what is displayed (if the label is Submit, don't put "Go" as a text image on the button) or if you have similar function like using an x to close a modal window and then using "close" on another one. Media player controls have consistent names, etc. I often see instances where the way things are named or called changes within the overall framework of the site.

Also raised by Sharron in [Survey on 3 Jun 2015](https://www.w3.org/2002/09/wbs/35532/EOWGTipsJune1/results#xdevelop)

**Comment by slhenry** [comment]
seems like this can be woven into an existing tip in Designing.

**Comment by iadawn** [comment]
Change 13c3e8f includes additional content to call out a couple of specific examples of this type of consistency in design. I think there may still be a slight issue in developing where, for example, image button text does not match alternative text. That is really more of an issue for alternative text though, and probably best captured in #151.

**Comment by sharronrush** [comment]
I am happy, can close this issue
