### ISSUE TITLE
Examples checkmark and X

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#263]
I noticed today the checkmarks and Xs are now on a gray circle. I think that attracts too much attention. I prefer how they were before.

**Comment by nitedog** [comment]
Hmmm. Without this styling the headings/captions were not sufficiently differentiated from the actual content below. Maybe we could reduce the gray intensity a little but I really like it now - it really helps organize the content visually, for me.

**Comment by slhenry** [comment]
My comment was ONLY about the dark gray CIRCLE around the check and X icons, which are now white. Previously the check and X was the same color as the text (or about the same), and not on a separate background.

I think @nitedog 's comment is about the light gray BAR background for the whole caption -- which is a totally different thing, and which really I like as is. :-)

**Comment by nitedog** [comment]
I do mean the circle around the tick and cross, to make them look more like icons. This works well now IMO.

**Comment by James-Green** [comment]
I agree with Shawn that the icons attract too much attention now.  We can't really go much more lighter on them (currently 5.74:1) and keep the text white.  What about making them white and the text either black or colored (i.e., green check, red x, blue i)?.  Check out these samples:

![screen shot 2015-09-22 at 12 28 18 pm](https://cloud.githubusercontent.com/assets/13589074/10026138/b521c082-6125-11e5-8f17-85e5ac52ee27.png)

**Comment by nitedog** [comment]
Thanks James! Yes, I totally love your colors. The important thing for me was to iconify the marks so that the caption better stands out as a header for the section. I think what you suggest are good visual landmarks to scan and organize the content. Thanks!

**Comment by slhenry** [comment]
Thanks for the option ideas, James!

I think the second option -- white circle, black symbol -- is the best for addressing both issues:
* helping distinguish the caption from the rest of the example
* not attracting too much visual attention

Possibly the colored symbols - toned down a bit - in white circle might be OK and not too attention-grabbing, but I'd need to see it on a page with lots of them.

**Comment by sharronrush** [comment]
I like using color because it personifies what the discussion is about, you may use color but not as the only indication of status.  I am find with toning the colors down a bit but think that some use of color is actually quite illustrative in this example.

**Comment by iadawn** [comment]
Implemented option 4 for viewing delectation.

**Comment by slhenry** [comment]
Thanks for trying it! It's still too attention-grabbing to me -- If I do the "squint test", the red Xs  jump out.

How about go back to the black checks and Xs -- as you had it at first -- and see what people think.

**Comment by slhenry** [comment]
Also, the square doesn't mean anything to me, and I find myself spending a bit of cognitive energy trying to figure it out.

Anyone have thoughts on another symbol for that? Perhaps just an empty white circle?

**Comment by iadawn** [comment]
Sorry, what square? This may be a font issue but if you could point me in the direction of where you are seeing a square.

**Comment by James-Green** [comment]
Perhaps add a little weight to the checkmark?  I do like the colors as another way of presenting the info.

**Comment by slhenry** [comment]
Colors are too distracting for me, but I'll let it go for now -- if you'll please tone down the green and blue. Thanks.

**Comment by slhenry** [comment]
[medium-high]
[ftr, "square" was browser rending error of an "i"]

Now that I see the ( i ) in a different browser, I'm concerned that they look like information icons -- e.g, like the ( i )s in the WCAG-EM Report Tool, e.g., <http://www.w3.org/WAI/eval/report-tool/#/audit/scope> that are clickable information boxes.

**Comment by slhenry** [comment]
[medium] Suggestion:
For the Designing and Writing examples, where there are (i)'s, I think they should be checks, e.g., <http://w3c.github.io/wai-quick-start/designing.html#ensure-that-interactive-elements-are-easy-to-identify> are all good examples.
For Developing, I would vote that no images is needed, and we can just do without the white circles all together. However, if image is important to some, could do something like mini-webpage/window for Rendered (e.g., <http://www.softicons.com/toolbar-icons/black-wireframe-toolbar-icons-by-gentleface/app-window-icon>) and mini "</>" for code.

**Comment by iadawn** [comment]
The </> icon is easy enough. I have added this in to let folks see what it looks like.

Strangley, a square icon comes with some problems that would make it a little bit more tricky to implement. Also, if you are looking for example, please use [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/). They are much, much easier to use.

Finally, I would not be in favor of having nothing. I think they serve well as a visual anchor for readers and help to distinguish the captions from the example that little bit more.

**Comment by nitedog** [comment]
I agree with not removing the "i"s.

**Comment by sharronrush** [comment]
I am OK with the i's I guess but don't really know what they mean.

**Comment by iadawn** [comment]
Added in a desktop icon instead of an 'i'. All icons are now implemented using SVG. Colors as suggested by @James-Green. Closing issue.

If there any immediate concerns regarding this issue, please do reopen.

**Comment by slhenry** [comment]
[low-medium] Blue means clickable on the Web. Can we make the Developing icons (rendered and code) not blue. I think the green of the checkmarks would work fine.

**Comment by James-Green** [comment]
Also... the desktop icons are not centered in their circles on Safari 7.1 OS 10.9.5 and Mobile Safari iOS 8.
![screen shot 2015-09-30 at 3 32 55 pm](https://cloud.githubusercontent.com/assets/13589074/10211449/1362497a-67b9-11e5-8538-0f887d93b56b.png)

**Comment by iadawn** [comment]
Unfortunately, the positioning seems to refuse to behave across browsers. Chrome and FF work fine. Not sure on IE as I write this, but I will check. I am open to suggestions for CSS fixes to this!

**Comment by slhenry** [comment]
ftr, I consider that the the desktop icons are not centered in their circles *very low priority*. Yes, it would be nice if we can figure it out, but it is not at all a showstopper -- nor necessarily worth a while lot of time to address.

**Comment by iadawn** [comment]
Closed. One outstanding point has been raised in #298
