### ISSUE TITLE
linko (typo of a link :-)

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#264]
under http://w3c.github.io/wai-quick-start/designing.html#provide-sufficient-contrast-between-foreground-and-background

For more information
WCAG
1.4.3 Contrast (Minimum) --> links to 1.4.1 instead of 1.4.3

Would be good to do a QA on all of these links :-)

**Comment by iadawn** [comment]
Done

**Comment by iadawn** [comment]
Interestingly there were a few problems because I had assumed a pattern. In QuickRef the root name from the TR is used as the anchor. Unfortunately, for some reason, sometimes this is prefixed by 'qr-' and I missed that.

**Comment by James-Green** [comment]
i'm going to use "linko" :)
