### ISSUE TITLE
WCAG links - handle first, then number

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#265]
Looking at the format of the links and the target of the links.
Currently links have number first, e.g.:
<blockquote>
* 3.3.2 Labels or Instructions (Understanding 3.3.2)
</blockquote>

However, the *target* of the links has the "handle" first and the number second. (details below)

Given that, and also that the number doesn't mean anything to beginners, I suggest we put the handle first and the number after it, e.g.:
<strong><blockquote>
* Labels or Instructions 3.3.2 (Understanding Labels or Instructions 3.3.2)
</blockquote></strong>
or possibly shortened to:
<blockquote>
* Labels or Instructions 3.3.2 (Understanding 3.3.2)
</blockquote>

DETAILS:
For example, under <http://w3c.github.io/wai-quick-start/developing.html#associate-a-label-with-every-form-control>

Quickref links - link target:
* h4 heading: "Labels or Instructions" <br/>then 3.3.2 is the first thing in the next paragraph
* page title: How to Meet WCAG 2.0
* URI: http://www.w3.org/WAI/WCAG20/quickref/#minimize-error-cues

Understanding links - link target:
* h1 heading: "Labels or Instructions" (bold)<br/>(line break) "Understanding SC 3.3.2"
* page title: Understanding Success Criterion 3.3.2  | Understanding WCAG 2.0
* URI: http://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html

**Comment by iadawn** [comment]
Done

**Comment by hkramer** [comment]
+1 seems like a sensible change
