### ISSUE TITLE
Contributions panel ("We welcome your ideas")

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#266]
The box at the bottom of the pages.

Draft idea for discussion:
<blockquote>
<strong>We welcome your input.</strong><br/>
Please send any ideas, suggestions, or comments via e-mail or GitHub.<br/>
[Fork & edit this page on GitHub] [Create new GitHub issue]<br/>
[Send e-mail to publicly-archived list: wai-eo-editors@w3.org]
</blockquote>

(Let's figure out the default for this overall, and then can update it on other relevant pages: Tutorials, Easy Checks, etc.)

**Comment by bakkenb** [comment]
Just another title idea:
"How can we make this page better? We welcome your input."

And change "send any" to "provide your" in the next line. Send is basically for email but is not correct terminology for GitHub:
"Please <b>provide your</b> ideas, suggestions, or comments..."

**Comment by slhenry** [comment]
Agree to change "send any". Maybe "share"?
"Please share your ideas, suggestions, or comments..."

**Comment by davidberman** [comment]
Very good. I would remove "We welcome your input", as redundant.

**Comment by James-Green** [comment]
What about @bakkenb's first sentence - it's asking a direct question.  We could follow it with a direct call to action like "Please let us know" and then just provide the choices?  spelling out the choices in text before the choices seems redundant.  Example:
> **How can we make this page better?**
> Please let us know...
> [Fork & edit this page on GitHub] [Create new GitHub issue]
> [Send e-mail to publicly-archived list: wai-eo-editors@w3.org]

**Comment by LydiaHarkey** [comment]
'Please let us know' sounds friendly and gives the impression we care about their feedback.
We could make the sentence more personal by using the word 'your'. 
ex. Please share your ideas, suggestions, or comments via email or GitHub.

**Comment by davidberman** [comment]
Perhaps eliminate the question structure altogether (always a good idea in an interface where there is no place to provide an answer), by replacing "How can we make this page better? Please let us know..." with "Tell us how to improve this page:"

**Comment by gheake-1** [comment]
I understand where David is coming from but Please let us know is more inviting and friendly, as Lydia stated. I believe people are cautious, in general about speaking up or making suggestions. It would be in our best interest in making it as inviting as possible to contribute.

**Comment by vmmiller** [comment]
How about a combination:
"We welcome feedback.  Please share with us your ideas, suggestions, or comments via email or GitHub."

**Comment by slhenry** [comment]
I think it would be good to present it with a tone & approach along the lines of: here's a resources that's started and we'd love your ideas/input on it, to help make it better -- rather than: this is done, give us your feedback/tell us how to improve it.

**Comment by sharronrush** [comment]
+1 to ...this is a start and we welcome your involvement and ideas

**Comment by AndrewArch** [comment]
+1 from me too to making it sound as though this is our draft and we welcome their input to polish it

**Comment by iadawn** [comment]
Contributors panel has been updated.

If there are still questions or concerns regardin thig, please do reopen the issue.

**Comment by slhenry** [comment]
[medium-high] I am still not comfortable with two buttons being gray and one being green. It make it look like the first two are disabled. 
(fyi, probably many, if not most, people using these pages will not have used GitHub.)

**Comment by slhenry** [comment]
[easy] There's still a typo in the pop-up for e-mail - in "archived"

**Comment by slhenry** [comment]
[medium-low] I'm not sure about the imperative "Help improve this page". Is it too demanding?
Perhaps "You can help improve this page."

**Comment by iadawn** [comment]
I personally don't think the imperative is too demanding. I can't imagine anyone being offended, put off, or feeling like they are being forced. I like the strength of the statement.

Typo fixed.

Open to suggestions on styling for the buttons. I am keen to keep them as buttons as the consistency is good and they stand out well as calls to action. I was looking for alternative styling options within WAI, but couldn't find anything for buttons. The only thing I found was the styling in the new [quick ref](http://w3c.github.io/wai-wcag-quickref/), but they are grey.

**Comment by slhenry** [comment]
Buttons: I like them as buttons -- just not that 2 are gray and 1 is green. Could just make them all gray for now.

[could save for later] On overview page, especially when there's only the first row of pages, the box stands out too much, I think. What about making the font smaller? and/or lighter?
Also, on the overview page, I suggest more space before the box to separate it from the main page content.

**Comment by iadawn** [comment]
One thought I did have was to completely remove the contributions panel from the Overview page. I decided to keep it as this was the most likely point for someone to suggest completely new areas for tips.

**Comment by davidberman** [comment]
Regarding the imperative, we find in general that plan language editors
embrace the imperative for when writing for the web.

Thank you for the fix,

David

On Wed, Sep 30, 2015 at 9:52 AM, Kevin White <notifications@github.com>
wrote:

> I personally don't think the imperative is too demanding. I can't imagine
> anyone being offended, put off, or feeling like they are being forced. I
> like the strength of the statement.
>
> Typo fixed.
>
> Open to suggestions on styling for the buttons. I am keen to keep them as
> buttons as the consistency is good and they stand out well as calls to
> action. I was looking for alternative styling options within WAI, but
> couldn't find anything for buttons. The only thing I found was the styling
> in the new quick ref <http://w3c.github.io/wai-wcag-quickref/>, but they
> are grey.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/wai-quick-start/issues/266#issuecomment-144408031>
> .
>



-- 
David Berman, RGD, FGDC
David Berman Communications | berman@davidberman.com | @davidberman | blog
<http://www.designedgecanada.com/author/david-berman>
+1-613-728-6777 | 340 Selby Avenue, Ottawa K2A 3X6

High Level Advisor, United Nations | GDC ethics chair | Ico-D
Sustainability chair | Carleton University Access Network chair
------------------------------
*Accessibility courses:* Ottawa | Europe | Vancouver | Victoria
*Upcoming:* Toronto | Mexico City | Dublin | Belfast | Korea | Bahrain
Watch David on CBS
<http://www.wtoc.com/story/17588481/scad-plans-revitalization> | Do Good
book news:  <http://www.dogoodbook.com/> <http://www.dogoodbook.com/>"Don't
just do good design ... do good!"

This message may contain proprietary information. Unauthorized
disclosure/copying/distribution of contents prohibited.

**Comment by iadawn** [comment]
Closed issue. Raised #299 to capture outstanding point.
