### ISSUE TITLE
checkmark, X, and i example icons need standardized alternative text

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#268]
In the code, it appears that they are just checkmark, x, and cursive i characters, on Safari Mac with VoiceOver, I'm hearing "heavy bound x" "check mark" and *nothing*, on focus for the three icons.

**Comment by iadawn** [comment]
These should all now have no alternative text read out. They are all (arguably) decorative icons.

Please feel free to reopen if you still have concerns.
