### ISSUE TITLE
What types of examples should be included?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#27]
Whilst working on the examples I have been including examples of bad practice as well as an example of good practice, for example, in [Don't use color alone to signify meaning](http://w3c.github.io/wai-quick-start/designing.html#dont-use-color-alone-to-signify-meaning). There are many ways to do things incorrectly and it may be that readers do not appreciate this idea. Should we simply not include examples of bad practice?

I appreciate that there are also many ways to do things correctly and that readers' correct solutions may not match any example given. However, it may be more helpful to still include at least one example of good practice where possible.

**Comment by AndrewArch** [comment]
I think both are worthy of illustration with common examples (e.g. graphs and forms as done for colour alone) - picture tells a thousands words (where applicable)

**Comment by sharronrush** [comment]
I agree with Andrew in principle - that what NOT to do can be useful as an example -  but I have a personal caveat.  I am one of those rare creature who does NOT prefer graphic illustration (infographics and such) because I do not process that very well.  In the examples here, I skimmed right past the pie charts and settled on the form fields because I was drawn to the text. I guess my point is to make sure that we varied examples.

**Comment by iadawn** [comment]
@sharronrush, thanks for that, I appreciate your perspective. In this particular example it may be difficult as the intended audience are visual designers. However, I can keep them to a minimum though.

**Comment by sharronrush** [comment]
Thanks, and actually my comment was not as strong as suggesting keeping them to a minimum. Your point is important that this is FOR graphic designers.  It was just a small reminder (and maybe an unnecessary one) that even for sighted folks, graphic illustration is not universally understood in the same way.

**Comment by melodyma** [comment]
Agreed with all the comments above. What not to do is just as important as what to do.

**Comment by AndrewArch** [comment]
Can I suggest in the revised example that we move the labels (%ages) off the graph, or ensure they meet contrast requirements :)

**Comment by hkramer** [comment]
People learn by comparison. I would leave in the "bad examples." Suggestion for "color alone" bad example: make the boxes next to the text solid and not just outline.

**Comment by bakkenb** [comment]
I agree with Howard and Andrew on this one. People learn fast by example. Some like illustrations of what to do, while others like illustrations of what not to do. When both are provided (when possible and/or appropriate) designers will pick up on the inferred "why it is good accessible design" or "why it is inaccessible design" quickly. An illustration is worth a thousand words, words of detail you won't have to add to the tip if the example illustrates it well. My vote is to use both as much as possible.

**Comment by schantzwebconsulting** [comment]
Keep both good and bad examples.  It may even be worth building a poster-size infographic (or just another page) of such examples.  Nudge, nudge, Sharron ;-)

**Comment by Egyrs** [comment]
+1 for bad examples too.

**Comment by Egyrs** [comment]
+1 to bad examples too.

**Comment by iadawn** [comment]
[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item06): Resolved to keep bad examples where appropriate
