### ISSUE TITLE
Include gray bars/icons for all examples

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#272]
_Not a showstopper for first version publication. >> Phase 2_

Not all examples have the gray bar with check/x icon.  It seems on those examples that the bar is "missing" (8 out of 22 are missing) and looks inconsistent. 

In order to create proper parallel structure, let's discuss adding the bar to all examples and using the **Example: text** for a high level (H3 level) description with the icon text being specific, as it's currently more or less used when bars are present.

For example:

> Example: Using color to convey meaning
> (x) Color only    (checkmark) Color and Symbol
> <example>       <example>
> 
> Example: Unique styles for different link states
> (i) Style links to stand out from text <example>
> (i) Mouse hover style <example>
> (i) Keyboard focus style <example>
> (i) Touch or click style <example>
> 
> Example: Labels and input fields associated by proximity
> <example>

could be modified to have a bar like this:

> Example: Labels and input fields associated by proximity
> (checkmark) Labels right aligned and adjacent to inputs
> <example>

More reason to do this: There are code snippets on Developing that have no bar.  If we really intend the code snippet icon for code, we should use it consistently on the page.

**Here are some screencaps with the bars on the left and the missing bars on the right...**
![screen shot 2015-09-25 at 9 27 18 am](https://cloud.githubusercontent.com/assets/13589074/10103036/6fd9ec04-6367-11e5-881e-02a00ac06a40.png)

**Comment by yatil** [comment]
I support this for Phase 2 :-)

**Comment by James-Green** [comment]
While it's still not a showstopper, I have been reading this on a mobile phone (visually and with Voiceover) and the need for "this is a good example" or "bad example" is even more evident to me on the smaller screen and very important when using a screenreader. I find myself worrying "is this example good or bad?" as arrive at each example...

**Comment by sharronrush** [comment]
We expect this to be resolved by the redesign, please close if no objection from @James-Green

**Comment by yatil** [comment]
I think this is now addressed.
