### ISSUE TITLE
Avoid CAPTCHA where possible: add link to CAPTCHA note

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#274]
Consider adding a direct link to the information that discusses CAPTCHA in 1.1.1

**Comment by nitedog** [comment]
That is, consider adding a link to the "Inaccessibility of CAPTCHA" report as "Background" to the tip. Even though this resource is quite dated, it still has quite some valuable information.
 - http://www.w3.org/TR/turingtest/

**Comment by iadawn** [comment]
Added and closed.
