### ISSUE TITLE
Mobile Layout Issue - email editors button/link

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#275]
![screen shot 2015-09-30 at 9 29 03 pm](https://cloud.githubusercontent.com/assets/13589074/10211557/049310fe-67ba-11e5-9d06-55fb320e4cb3.png)

Seen on Mobile Safari iOS 8 iPhone 5s.

**Comment by iadawn** [comment]
This is related to #266 and a comment that @slhenry concerning the visibility of the email address.

I would propose changing this button to 'Email EO Editors'. This allows it to fit well in the mobile view, and keeps it short. The e-mail address for WAI editors also appears in the footer, so I don't know that any information is being hidden.

**Comment by slhenry** [comment]
I think many people would miss it in the footer, so I don't think that's a sufficient solution.

Another idea: Put it in the text above: "Please share your ideas, suggestions, or comments via email to the publicly-archived list wai-eo-editors@w3.org or via GitHub." Then the button could just be "E-mail".

(Also somewhere else I suggested making the font smaller for all of it. :-)

**Comment by iadawn** [comment]
I am not really a fan of exposing email addresses like this; I think the action is to send the email, not to know the email address. However, it is not a strong feeling in this case.

Change made. Closing :)
