### ISSUE TITLE
In Writing, should 'Expand all acronyms on their first use' be removed?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#28]
Refers to [Expand all acronyms on their first use](http://w3c.github.io/wai-quick-start/writing.html#expand-all-acronyms-on-their-first-use) tip in 'Writing'.

This is quite a specific tip and may not be the most important thing to consider in comparison with other tips.

**Comment by AndrewArch** [comment]
I do consider it an important issue in terms of 'making the writing clear - vote to keep

**Comment by sharronrush** [comment]
Also, this has become less crucial as AT can now be set to read all caps as acronyms rather than pronounce as a word.  I am on the fence, no strong feelings either way, but don't consider this to be a critically important tip.

**Comment by melodyma** [comment]
It has similar specificity to some of the other ones and there's no overlap either.

**Comment by AndrewArch** [comment]
Sharron, it's not about how a screen reader handles CAPS, but about helping everyone understand the acronym [e.g. Web Content Accessibility Guidelines (WCAG) ]

**Comment by sharronrush** [comment]
Duh! Of course that makes sense Andrew. Comment withdrawn :)

**Comment by hkramer** [comment]
No, I would LII (Leave it in).

**Comment by slhenry** [comment]
I don't feel strongly either way. Certainly it is of lower importance than the other things. If we leave it, probably it should be last.

**Comment by bakkenb** [comment]
Here is my take on the comments above. Based on the comment about AT being able to properly read all caps acronyms, if this is relevant and an issue for those using AT, then I think this tip should be left in. On the other hand, if it is not about how AT handles all caps, but just about understanding what the acronym stands for, then this is not an accessibility tip for helping people with disabilities access web content and should not be included. If the latter is true, it is true for all users and not limited to just web content but to all writing formats and should not be included in an accessibility tips site.

**Comment by schantzwebconsulting** [comment]
This is as much a question of writing style as it is of understanding/accessibility.  As such, it's a tip that's probably better understood than most, and can safely be moved to the end of the list.

**Comment by Egyrs** [comment]
+1 to keep it.

**Comment by AndrewArch** [comment]
Also noting that this specifically help people with cognitive issues
Furthermore, isn't this similar to "avoid complex language"?

**Comment by iadawn** [comment]
[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item02): Resolved to keep this tip and move it to the bottom of the list
