### ISSUE TITLE
Mobile Layout Issue - Page Title examples truncated on Developing

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#280]
![screen shot 2015-09-30 at 9 38 39 pm](https://cloud.githubusercontent.com/assets/13589074/10211702/6dda6a98-67bb-11e5-95a6-60f95633af77.png)

Seen on Mobile Safari iOS 8 iPhone 5s.

**Comment by iadawn** [comment]
This is captured in #187.

The solution adopted for the moment avoids other more problematic issues although it remains open to address.
