### ISSUE TITLE
Screenreader Issue - VO reads bullets as separate links

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#282]
VO reads each bullet in the main nav as a separate link called “black square, link” – it seems VO likes to do this with bullets, but can they not be links?
![screen shot 2015-09-30 at 9 42 35 pm](https://cloud.githubusercontent.com/assets/13589074/10211739/0acd31f0-67bc-11e5-8085-04da0078dc74.png)

iOS 8 Voiceover with Mobile Safari

**Comment by iadawn** [comment]
I am not sure where you are seeing this problem. I have tested with VO in OSX and the items in the primary nav are read as links and there is no mention of black squares. This is in OSX 10.10.5.

**Comment by James-Green** [comment]
See if you can replicate on your iPad.  This was iOS, and I know iOS VO likes to grab and read every element it can, but for some reason, those bullets were being read as links that you can click on, but don't do anything.

**Comment by iadawn** [comment]
I checked with iPad and, sure enough, they are read out. This is not something that happens in VO on OSX so I think this is an issue with iOS VO implementation. The navigation is coded correctly so I don't think there is anything that we can do to address this.

Closing issue. If you feel that we should investigate further, please reopen.
