### ISSUE TITLE
Screenreader Issue - >> reads as "right double arrows" not "current page"

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#283]
VO reads the >> indicating current page as “right double arrows” which without the visual context does not imply “current page” very well.  Could we add "current page" on the main nav as it's done in the subnav?  

![screen shot 2015-09-30 at 9 46 22 pm](https://cloud.githubusercontent.com/assets/13589074/10211768/721accbe-67bc-11e5-92db-3dec25ee5ad6.png)

iOS 8 Voiceover with Mobile Safari

**Comment by iadawn** [comment]
This is a site-wide issue that is beyond the scope of this resource

**Comment by James-Green** [comment]
i thought that might be the case...

**Comment by slhenry** [comment]
moved to https://github.com/w3c/WAIsite/issues/2
