### ISSUE TITLE
Screenreader Issue - alt for characters graphic

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#284]
![screen shot 2015-09-30 at 9 49 05 pm](https://cloud.githubusercontent.com/assets/13589074/10211799/d3da6644-67bc-11e5-81c3-23bd262e6121.png)

The alt for this image is “characters from different languages” so VO reads “characters from different languages translations, link” which is a little confusing with the “characters from” included.  If "characters from" was removed, VO would read "different languages translations, link".

iOS 8 Voiceover with Mobile Safari

**Comment by iadawn** [comment]
This is a general issue with the WAI site and beyond the scope of this resource.

**Comment by James-Green** [comment]
ok!

**Comment by slhenry** [comment]
moved to https://github.com/w3c/WAIsite/issues/1
