### ISSUE TITLE
Screenreader Question - Share Links precede H2s in code order

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#285]
![screen shot 2015-09-30 at 9 50 52 pm](https://cloud.githubusercontent.com/assets/13589074/10211830/20524fc8-67bd-11e5-817c-bd830e5955d2.png)

Share links precede H2s in the code order, do we want them to follow instead?

**Comment by iadawn** [comment]
It is a simple matter to change the order of the DOM. However, it is quite challenging to ensure that for the first title on the page, the share link is on the right, the heading wraps around it properly, and there is no overlap into the About WCAG panel.

**Comment by iadawn** [comment]
Found a solution, don't know that it is a solution that would allow the permalink code to work anywhere, but it works for this.
