### ISSUE TITLE
Screenreader Issue - alt for page titles in Writing

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-quick-start#292]
In Writing, Page title examples have alt text reading as the same as the caption.  This doesn’t provide the information in the text of each example image.  E.g., alt for Home Page Title image should read something like“Title bar with the text, “Space Teddy Inc.” 
![screen shot 2015-09-30 at 10 12 59 pm](https://cloud.githubusercontent.com/assets/13589074/10212080/2780c40c-67c0-11e5-823a-1fca97a2ffa1.png)

**Comment by iadawn** [comment]
In this case it seems more appropriate to remove the `role='img'` from the SVG as the main content of the SVG is the `<text>`. Doesn't so reads the example as expected.

**Comment by James-Green** [comment]
sounds good.
