### ISSUE TITLE
Change category titles

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#296]
[Comment received](https://lists.w3.org/Archives/Public/wai-eo-editors/2015Oct/0000.html) from Kazuhito Kidachi <k-kidachi@mitsue.co.jp>.

> I think "Tips for Getting Started" content seems great starter kit for 
newbies, but its categories seem a bit confusing. My suggestion for 
its structure is:
> 1. Visual Design for Web Accessibility
> 2. Content Authoring for Web Accessibility
> 3. HTML Coding for Web Accessibility
> The words like "Designing" "Writing" "Developing" seem to have broader 
scope of meaning, so...

**Comment by iadawn** [comment]
Suggested response, this would need appropriate topping and tailing, but this is the core content:

The approach to naming the categories was subjected to lengthy consideration at the early stages of the development of this resource. The aim was to provide a title that was short but descriptive of the broad project activity. We also avoided making reference to specific project roles as there is so much variation in job terminology.

Your suggestions are welcome but following discussion the feeling is that they may be too restrictive in their scope or may introduce terminolgy that some might find unclear. Specifically:

* Designing covers elements of user interface design as well as visual design.
* Content Authoring is sometimes used more broadly to cover the writing of code or creation of multimedia or imagry.
* Developing covers other technologies including JavaScript, CSS, and ARIA.

Thank you for your suggestion, it was helpful for us to review the categories and consider how they are presented. In this particular instance the decision is to leave the titles as they are.

**Comment by bakkenb** [comment]
I like a combination of the first and second suggested responses. It gives a little bit of a reason why the suggestion will not be implemented.

**Comment by gheake-1** [comment]
I think the categories should remain as is. I think they are succinct and easy to follow for a wide audience.

**Comment by James-Green** [comment]
I like your suggestion and support the stance.

**Comment by AndrewArch** [comment]
Response supported.

**Comment by davidberman** [comment]
I support iadawn's position and explanation.
