### ISSUE TITLE
Content section Highlight & Focus on the page are not the same

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-quick-start#302]
Issue : On Selecting a content menu item, the page loads correctly. But, the content section highlights the previous link. See screenshot below.
Sample url : http://w3c.github.io/wai-wcag-quickref/#time-limits
![image](https://cloud.githubusercontent.com/assets/15111528/11241604/325964e0-8e50-11e5-8321-28a463da4aed.png)

**Comment by yatil** [comment]
Hi @HerinHentry,
we have an error in the URL to submit issues in the email, I have moved your issue to the correct repository. You can find it, and subscribe to notifications, here: w3c/wai-wcag-quickref#66.

Best, Eric
