### ISSUE TITLE
Highlighted Content link _ On Hover fails contrast

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-quick-start#303]
When the content link is highlighted, mouse hover on the link fails is not readable. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/15111528/11241863/27cd820c-8e52-11e5-8f74-fe825ba9b37b.png)

**Comment by yatil** [comment]
Hi @HerinHentry,
we have an error in the URL to submit issues in the email, I have moved your issue to the correct repository. You can find it and subscribe to notification here: w3c/wai-wcag-quickref#65.

Best, Eric
