### ISSUE TITLE
back to page contents links

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#308]
I think after each section there should be a link up to the page contents, e.g., https://www.w3.org/WAI/intro/people-use-web/principles#toc

**Comment by iadawn** [comment]
I am not averse to this (although the back button will do the job more effectively) but I have a couple of reservations with the style of the links in general use.

As they are styled, they are much more visually salient than the, more important headers. I think this contributes to the difficulties in cognitively breaking up the page into manageable reading chunks.

If this were to be done, I would recommend a more subtle approach to styling. The link is important but not so important that it should own the page.

**Comment by slhenry** [comment]
agree

**Comment by sharronrush** [comment]
I don't see the need for the back to top link at all but certainly agree that if it is used, it should be less attention-drawing

**Comment by yatil** [comment]
I think this has been addressed in the redesign.
