### ISSUE TITLE
"provide a variety of navigation options"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#32]
For example, search in addition to hierarchical menu. Seems missing from our tips. Could fit under "provide clear and consistent navigation" in Design Tips but could also be a separate tip - possibly even in Developing Tips.

**Comment by iadawn** [comment]
Yes, agree that this is missing.

It might fit in 'clear and consistent navigation'. Maybe as something like 'Provide clear and consistent navigation options', and then expand the text appropriately?

I would probably see this more as a design tip... if how it was implemented had accessibility implications then Developing would be appropriate.
