### ISSUE TITLE
Remove empty <p></p> from first <figure> about styling links

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-quick-start#325]
Separating this from issue #319 at the end of this comment: https://github.com/w3c/wai-quick-start/issues/319#issuecomment-270143498

There is an empty `<p></p>` element in the first figure for styling links in the section about ensuring interactive elements are easy to identify at: http://w3c.github.io/wai-quick-start/designing.html#ensure-that-interactive-elements-are-easy-to-identify

**Comment by yatil** [comment]
Feel free to press the pen icon on that page and remove the empty `<p></p>` from line 202:

https://github.com/w3c/wai-quick-start/blob/master/source/designing.html.erb.md

(Click green buttons several times to create a pull request. You can mention this issue in the commit, like so: `fixes #325`.)

:-)
