### ISSUE TITLE
[Tips pages] breadcrumb

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#338]
This comment came into Editors list <https://lists.w3.org/Archives/Public/wai-eo-editors/2017Aug/0006.html>

> Also, you are not following your own advice about breadcrumbs. The only link I see at the top left is Home. Disabilities is surely a subsection of something else, and not available directly from your home page?

**Comment by bakkenb** [comment]
Will the breadcrumb issue be addressed when we launch redesign?

**Comment by yatil** [comment]
Disabilities is not a subsection of something else (on the WAI site). The tips are and we will have proper breadcrumbs with the redesign.

**Comment by yatil** [comment]
Obsolete
