### ISSUE TITLE
Tips Overview page missing from main navigation

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#343]
Links in main navigation are only to the sub-pages, and not the overview: https://www.w3.org/WAI/beta/tips/

**Comment by yatil** [comment]
That was a conscious design decision as the tips come up in different places. @slhenry and I have talked about getting rid of the overview page altogether and instead using a box to connect the individual tips pages. But nothing is set in stone here :-)

**Comment by slhenry** [comment]
Correct. Current plan is to not have a Tips Overview page.

I went back over the overview page, and don't think we're losing much by not having it. The one thing that is missing in the redesigned pages is "Getting Started". I note that's included in the titles I wrote elsewhere, but not in the actual titles. I will tweak the titles of the pages so "Getting Stated" is included.

If someone is on one Getting Started Tips page, we do want them to know about the others. Right now that is provided by the left nav for "Design & Develop". Later when we have Tips under other nav areas, we will probably add a box like is on the current website.

If you want to point someone to a place where they can find Tips (and more) for different roles, you can point here: <https://w3c.github.io/wai-website/audiences/>

Closing this issue for now.
Shadi and others feel free to reopen it if you want more discussion.
