### ISSUE TITLE
Inline Example - Heading Levels number description

### ISSUE THREAD

**Issue by denishowe** [w3c/wai-quick-start#353]
https://www.w3.org/WAI/tips/writing/
Section "Use headings to convey meaning and structure"
2nd inline example "Using headings and subheadings"
Subsection "Heading Levels"
Text: "The lower the number, the smaller and more detailed a section."
Replace with: "A higher number indicates a more specific, more detailed subsection."

**Comment by slhenry** [comment]
@denishowe Thanks for taking the time to note that.

**Comment by slhenry** [comment]
HI @denishowe 

I'm cleaning up old issues. Letting you know we decided that sentence is just in example text, is confusing either way, and is not necessary. So we deleted it.

Thanks again for pointing it out to us!
