### ISSUE TITLE
Inaccurate text for the triangle images

### ISSUE THREAD

**Issue by frirasyidi** [w3c/wai-quick-start#394]
The descriptive text in the [Don’t use color alone to convey information](https://www.w3.org/WAI/tips/designing/#dont-use-color-alone-to-convey-information) section of `/tips/design/` document is as the following:

- Green triangle: Angles are 30°, 60°, 90°
- Blue triangle: Angles are 30°, 30°, 120°
- Red triangle: Angles are 30°, 60°, 90°
- Yellow triangle: Angles are 40°, 70°, 70°

while based on the image, it should as below:

- Green triangle: Angles are 30°, 60°, 90°
- Blue triangle: Angles are 30°, 30°, 120°
- Red triangle: Angles are 40°, 70°, 70°
- Yellow triangle: Angles are 60°, 60°, 60°

The shown image:

![Screen Shot 2023-11-24 at 17 16 07](https://github.com/w3c/wai-quick-start/assets/4636602/32aea1ae-eb61-460d-8c87-429171a2f6e4)

**Comment by remibetin** [comment]
@frirasyidi Thank you so much for spotting this! I have opened a PR to fix this: https://github.com/w3c/wai-quick-start/pull/395
