### ISSUE TITLE
order of "learn more links"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#40]
I think the order of the links should be fairly consistently throughout all tips. Where appropriate, the suggested order would be:
 - Link to any related Success Criteria in QuickRef
 - Link to any related sections in Easy Checks
 - Link to corresponding sections in Understanding WCAG 2.0
 - Link to any relevant user stories in How People with Disabilities Use the Web
 - Any other links specific to the topic, like business case, tools list, etc etc

Please consider this in combination with #39

**Comment by hkramer** [comment]
I agree with the order presented above which seems to be the way the current draft is laid out. (This is not a question btw).

**Comment by slhenry** [comment]
I like that order in general. I think it should be the starting point; however, I do not think we have to stick to it rigidly -- we should be OK with being inconsistent in order in cases where there is a compelling reason to do the order differently.

**Comment by bakkenb** [comment]
Agree with comments above.

**Comment by nitedog** [comment]
"compelling reason" is the key point. yes, where needed we can deviate. but right now i feel there is too much inconsistency without apparent reason. it seems arbitrary and is somewhat confusing IMO. I think we should have a relatively high threshold for deviating from a consistent pattern.

**Comment by schantzwebconsulting** [comment]
I vote for consistency.

**Comment by AndrewArch** [comment]
I'll also vote for consistency

**Comment by Egyrs** [comment]
I agree. The consistency is important too.

**Comment by iadawn** [comment]
[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item04): Resolved to ensure consistency in presentation order of links
