### ISSUE TITLE
Merge Keep it short and simple and Avoid using complex words

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#41]
From @slhenry in #29:

* It is pretty redundant with the next point "Avoid using overly complex words and phrases". Maybe these ought to be combined , or further differentiated?

**Comment by iadawn** [comment]
I would disagree on this. For example, consider the sentence:

> Check the pharynx for inflammation

This is both short and simple, however it involves complex words that could be avoided for general audiences.

> Check for swelling in the throat

Just as short and simple, but now also not complex.

One could certainly argue that 'simple' would suggest the modifications in the alternative version of the example. However, I think that there is sufficient need to draw this out as a specific item as it is often overlooked.

**Comment by slhenry** [comment]
I disagree that "pharynx for inflammation" is simple :-)

**Comment by iadawn** [comment]
[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item03): Resolved to keep these two issues separate.
