### ISSUE TITLE
intro blurb

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#43]
"These introductory tips cover the basics of accessible user interface and visual design." - have you considered using the phrase "get started" somewhere, maybe also for SEO purposes? For example:
* "These introductory tips help you get started with the basics of accessible user interface and visual design."
* "These getting started tips introduce the basics of accessible user interface and visual design."
* "These introductory tips cover the basics of accessible user interface and visual design, to help you get started."

**Comment by iadawn** [comment]
Hadn't been considered within the paragraph text... I am not sure how much SEO value this brings. The phrase is already in the primary navigation, the section navigation, and the primary section page.

I could be introduced into the initial paragraph, although it would raise the usual concerns of whether or not the introduction is then sufficiently terse.

**Comment by iadawn** [comment]
Closing this comment in preference to discussion in pull requests #125 and #126. Feel free to reopen if there is more to this not covered.
