### ISSUE TITLE
sufficient contrast - tools

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#45]
"A minimum contrast ratio is required by the guidelines *and tools are available* ..." - how about "and guidance on how to check is available"? Rationale: there is a "how to" link in the "learn more" section, which is what we want people to use for this, rather than a reference to a tools list that is either outdated (understanding doc) or a general tools list.

**Comment by iadawn** [comment]
Agree to the change, although I worry that Easy Checks is more supportive of evaluation when code is available and subject to the same problem of going out of date - although really it only links to the Juicy Studio checker so may not be a problem.
