### ISSUE TITLE
Section Nav box design

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#51]
I think we want to use different colors for this. The Page Contents box on the other pages uses the orange color for the links because they link to orange headings on the page. But this is different -- it links off the page.

Really this is redundant with the main navigation. How about using the colors of the main navigation? (light blue background with blue links)?

**Comment by iadawn** [comment]
I am not sure what you mean when you say the 'Page Contents box'; could you link to an example?

The section navigation was added to provide consistent visible access to the other pages in this resource, as it was felt that the main navigation was not sufficient for visitors who reached the page via a direct link.

I would not be keen on using the colors from the primary navigation for two reasons: firstly, I think that this would create a significant visual imbalance at the top of the page, secondly, I think that it would take away from this section navigation working to link together the various tips pages.
