### ISSUE TITLE
Explain Learn More links

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#52]
I think we need to give some explanation about the Learn More links. Hopefully we'll get newbies to these pages -- that's the primary target audience. :-) Many won't know WCAG -- and they could get lost/confused/overwhelmed by the links throwing them into the middle of complicated resources. So it seems we need to do some explanation up front... although we wouldn't want to add much more text at the top... Maybe we present it as "About the Learn More links" that's expandable-collapsible? ;-)

**Comment by iadawn** [comment]
Which learn more links are you referring to? The ones specific to each tip or the general ones on each page?

If I assume the former then, are you suggesting a standard block of information to be presented for each of the Learn More sections? Do you have a suggestion for what this might say?

Is the problem with the WCAG reference specifically or all the links? If it is with the WCAG one, would there be a better way to present that?

**Comment by iadawn** [comment]
As discussed, I will look at exploring options to include a 'What is WCAG'-type panel within the each page
