### ISSUE TITLE
Focus indication - consistency with Easy Checks

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#60]
The example of visible focus seems to say that it is OK to have the dotted line as focus indication for keyboard focus, even when the hover focus is more visibly prominent.  And yet, in EasyChecks, we say "All functionality by keyboard: [snip] ... you don't need the mouse to activate actions, options, visible changes, and other functionality."

In our discussion, we agreed that keyboard focus indication had to be equivalent to mouse hover indication but this Tip does not seem consistent with that position.

**Comment by iadawn** [comment]
Just wanted to check what you thought made the hover focus more visibly prominent; it only has the color change. The tabbed to has a color change and a border.

I recall the discussion on these items. I may have missed the final statement on making hover and focus the same. Can I just confirm this is the case and I can amend the example?

**Comment by sharronrush** [comment]
hmmm, seems I may have missed the color change and assumed we were relying only on the dotted line. Point withdrawn, thanks.
