### ISSUE TITLE
Suggested example for clear and concise

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#61]
In the event of a vehicular collision, an company assigned representative will seek to ascertain the extent and cause of damages to property belonging to the parties involved.  Once we obtain information that causes us to understand the causality, we will assign monetary remuneration accordingly.

If our client is involved in a car accident, an agent will investigate. Those findings will determine the payment of claims.

**Comment by iadawn** [comment]
😃 Love it!

Were you an insurance copy-writer in a past life?!!

**Comment by sharronrush** [comment]
No, but I sure have had to try to decode plenty of insurance communications, those guys are baaaaaddddd!
