### ISSUE TITLE
Edit suggestion for Provide meaningful headings...

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#62]
The use of clear heading structure allows many users to navigate and process content more effectively.  Headings should be short, descriptive, and relevant to the specific content of the following section.

**Comment by iadawn** [comment]
I like the second sentence, but I am concerned that the first one veers a bit too much into the 'why'. What about:

> Headings should be short, descriptive, and relevant to the specific content of the following section. Use headings to split up text into manageable chunks to help navigation and comprehension.

One thing I was interested in including was reference to avoiding metaphor and puns in headings. Worth it? For example, something really simple like:

> Avoid using metaphor and puns in headings.

**Comment by slhenry** [comment]
I [strongly] do not think we should say anything about metaphor and puns in headings. I think that's not a common important problem.

(I'm happy to talk through the other points, but am having trouble typing them up)

**Comment by AndrewArch** [comment]
+1 to Kevin - Sharron's "Headings should be short, descriptive, and relevant to the specific content of the following section." is good, but the first sentence suggested is not so much a tip. 
What bout "Headings should be short, descriptive, and relevant to the specific content of the following section to aid comprehension." as a compromise?

+1 to Shawn - this is not an issue I come across very often at all.

**Comment by iadawn** [comment]
To try to address this @slhenry's concerns, I have changed the first sentence to:

> Use clear and simple headings to group related paragraphs.

Related to [discussion in EO Meeting 24 July](http://www.w3.org/2015/07/24-eo-minutes.html#item01).

**Comment by slhenry** [comment]
OK.

**Comment by iadawn** [comment]
Closing on assumption that 'OK' means concern has been addressed. If not, please feel free to reopen.
