### ISSUE TITLE
Edit to  Page Title

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#63]
Assign unique titles to each page within a website that simply describes page content and distinguishes it from other pages. When pages have a group relationship, for example as part of a multi-step process, put the unique part at the beginning of the title, followed by the common descriptor.

Note: we would want to be sure to have an example of that.

**Comment by iadawn** [comment]
I have incorporated elements from your suggestion. If you feel there is still more required, just say, otherwise, feel free to close this issue.
