### ISSUE TITLE
Omit passive voice

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#68]
Rather than "Forms should provide..."  I suggest the following:

Provide clear instructions about required information formats. Where possible, use back-end processing to correct formatting errors. For example, accept phone numbers that include spaces and delete the spaces as needed. Clearly identify errors that cannot be auto-corrected, including a description of the specific error, where it occurred, and how to correct it.  Provide an in-page link for easy access when feasible.

**Comment by iadawn** [comment]
Incorporated some of your suggested changes. If you are happy with the changes, I will close the issue (or you close if you can 😀)
