### ISSUE TITLE
Change 'Create designs for different viewport sizes'?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#69]
Comments on the [Create designs for different viewport sizes](http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes) in issue [#53](https://github.com/w3c/wai-quick-start/issues/53#issuecomment-118117736) suggest that there may be some issues with this tip.

The main concern was that the SC specified was not necessarily relevant. This tip was originally related to providing good font-sizes, but changed following feedback to something more related to responsive design.

Should this tip be changed? or is it ok to have a tip without a specific related SC? (Note in managing, evaluating, writing, and advocating it is likely that there will be many tips without SCs)

**Comment by bakkenb** [comment]
Thanks for the explanation Kevin. I am still in the belief that the "WCAG Requirement: 1.4.4" does not apply and should be removed for this one. I like the tip as it is, I just don't think it should reference 1.4.4.

**Comment by sharronrush** [comment]
+1 to removing 1.4.4 reference.

Also passive voice is confusing, suggestion for editor's discretion:

Consider how page information is presented in different sized viewports, such as mobile phones or zoomed browser windows.  Allow for changes in position and presentation of main structural elements to use space most effectively. Ensure text size and line width are set to maximize readability and legibility.

**Comment by vmmiller** [comment]
+1 to remove 1.4.4
+1 for description above, it's a bit simpler and easier to understand.

**Comment by LydiaHarkey** [comment]
I like the tip as is but I wondered if the reference WCAG requirement  1.4.4 changed, what would the reference change to?

**Comment by nitedog** [comment]
We should check with WCAG WG and the Mobile TF. It seems that 1.4.4 could be at least related - there is a related thread on the WCAG WG mailing list: https://lists.w3.org/Archives/Public/w3c-wai-gl/2015JulSep/0013.html

**Comment by yatil** [comment]
There are a few things in the [Mobile Accessibility: How WCAG 2.0 and Other W3C/WAI Guidelines Apply to Mobile](http://www.w3.org/TR/mobile-accessibility-mapping/) document, in the sections [Small Screen Size](http://www.w3.org/TR/mobile-accessibility-mapping/#h-small-screen-size) (relates to Principle 1) and [Consistent Layout](http://www.w3.org/TR/mobile-accessibility-mapping/#h-consistent-layout) (relates to Principle 3). The latter one cites the following success criteria:

*    3.2.3 Consistent Navigation (Level AA)
*    3.2.4 Consistent Identification (Level AA)

I think it would be good to refer to the sections in the “Apply to Mobile” document.

**Comment by AndrewArch** [comment]
+1 to keeping the tip. Not so sure about linking to 3.2.3 or 3.2.4 - do these rely apply?

**Comment by iadawn** [comment]
Closing.

With changes in introduction to higlight that these are not all requirements, the need for a mapped SC is less important. I have linked in the [Small Screen Size](http://w3.org/TR/mobile-accessibility-mapping/#h-small-screen-size) from the Mobile Accessibility Mapping document, which is relevant background information.

**Comment by yatil** [comment]
👍
