### ISSUE TITLE
Designing Tip: Make all functionality available from a keyboard.

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#70]
Is this important for web user interface design? What about in the world of mobile? Or is it mostly just a coding/markup issue?

(Once upon a time -- wayyy back when context menus from right-mouse-click was very new -- a designer provided some functionality only from that context menu. During usability testing, the users could not figure out how to get to the functionality because they didn't know context menus yet. Also, it was not available to non-keyboard users.)

In web & mobile design today, do designers sometimes spec out a UI that requires mouse?

**Comment by iadawn** [comment]
I would [strongly] argue that this is a developing issue. I get the example you are making, but I have not seen anything like that in any project I have encountered.

That is not to say that this wouldn't happen, just that it is probably not common enough a problem to suggest a designing tip.

**Comment by slhenry** [comment]
ok. I fine with not raising it for EOWG input.
