### ISSUE TITLE
Designing Tip: Movement

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#71]
Pause, Stop, Hide 2.2.2/2.2.3; Three Flashes 2.3.1/2.3.2

These certainly are designing issues. I think moving content is fairly common -- e.g., on home pages. It seems we should have a tip to address Pause, Stop, Hide.

At this point I'm [medium] on it, but could be talked into low or high. :-)

Flashing is less common, so probably we don't mention flashing in these tips.

**Comment by iadawn** [comment]
My two thoughts on this are:

1. How common a problem is this. I agree moving content is common... I don't know about 'fairly' common
1. I think this would be hard to convey meaningfully as a designing tip

Overall, I think I am [low-medium] which suggests that it is not reaching a reasonable threshold for inclusion.

**Comment by slhenry** [comment]
1. I think very common. e.g., https://www.arkadin.com/ , http://www.mdanderson.org/ ,  http://cancer.stanford.edu/ , http://www.wisc.edu/

2. first quick start to get your juices going: If content or images change, provide a way for users to control it

**Comment by iadawn** [comment]
1. Ah, carousel type things. Ok... I will give you a tad more than 'fairly' 😉
1. Ok, so if we are to drop a tip in favour of this one... which tip goes?

**Comment by yatil** [comment]
KI(PT)SS[1]: 

> Ensure that animations are stoppable
> 
> When designing animations, provide controls or mechanisms to stop them. This applies to videos, carousels and image sliders as well as to UI animation.

[1] Keep it probably too super simple ;-)

**Comment by iadawn** [comment]
[EO Meeting 10 Jul](http://www.w3.org/2015/07/10-eo-minutes.html): Resolved to create a tip for this to allow comparison with all other tips.

**Comment by AndrewArch** [comment]
Agree this tip is needed to address the issue of new banners and the like.

**Comment by iadawn** [comment]
[EO Meeting 17 July](http://www.w3.org/2015/07/17-eo-minutes.html#item04): resolved to keep this tip.
