### ISSUE TITLE
Designing Tip: Change of context

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#72]
On Focus 3.2.1 (When any component receives focus, it does not initiate a change of context.)
On Input 3.2.2 (Changing the setting of any user interface component does not automatically cause a change of contex)

Is this not common enough to warrant a Tip? I still see the problem of drop-downs used as menus that automatically select with keyboard, so users can't get past the first item.

Maybe this is kinda hard to explain and thus not a beginner's tip?

**Comment by iadawn** [comment]
I think I would agree with your last comment.

**Comment by slhenry** [comment]
ftr (for the record), when thinking about Developing, I came again to this issue. I'm mildly uncomfortable leaving it out all together; however, I'm OK with it. :)
