### ISSUE TITLE
Designing Tip: Images of Text

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#73]
(SC 1.4.5 If the technologies being used can achieve the visual presentation, text is used to convey information rather than images of text...)

Certainly this is a designing issue. Perhaps we should have a Tip on it?

**Comment by iadawn** [comment]
Actually, I would [strongly] argue that this is not a designing issue. Any visual design will have images of text, how that is implemented in developing will need to consider how text is handled.

**Comment by slhenry** [comment]
Hum. The designers specify text. Ideally they would understand the issue of text being real text and not images of text. Otherwise, they are more likely to design text in such a way that it cannot reasonably/easily be presented as real text. -- e.g., fancy gradient in the letters themselves.

**Comment by yatil** [comment]
I’m really undecided on this, there are possibilities to use textured text using [CSS masks](http://viget.com/inspire/easy-textures-with-css-masks) which can be easily applied but are supported _differently_ in different browsers ([see CanIUse.com](http://caniuse.com/#feat=css-masks)). The designer needs to be aware that [websites don’t look the same in every browser](http://dowebsitesneedtolookexactlythesameineverybrowser.com/) and explore fallbacks with the developer. Those issues are really on the intersection between (theoretical) design and (practical) implementation.

**Comment by iadawn** [comment]
I have had a long held suspicion that a lot of the desire/demand for pixel-perfect-must-look-the-same view stems from print trained designers and those ideas still being prevalent. That is a separate issue to a certain extent though.

To a certain extent I still feel that the act of designing should be platform/code agnostic, or at least not overly concerned with code. Yes, there will inevitably be a discussion on how certain approaches are rendered in code, but that is a) not necessarily a getting started issue and b) much more than simply designing.

**Comment by AndrewArch** [comment]
this is still an issue in the online advertising sector, but not sure it warrants a 'getting started' tip

**Comment by iadawn** [comment]
[EO Meeting 17 July](http://www.w3.org/2015/07/17-eo-minutes.html#item04): resolved not to include this tip.

**Comment by MartinDesigner** [comment]
Not only Wordpress or Joomla is the key from Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
