### ISSUE TITLE
Designing: color alone example

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#74]
1- I think the example with the triangles is still unnecessarily complex and distracting. My mind is first trying to differentiate between the before and after, then trying to sort out the question, then realizing "what the heck does this question have anything to do with the tip?!". Why not just the accessible triangles with the correctly placed labels, and a description/caption for the example that explain this?

2- The colors are just too vivid and loud IMO. They scream, especially the yellow, blue, and green.

**Comment by vmmiller** [comment]
1. I think the triangles example is puzzling.   Sshh... don't tell anyone ... I liked the pie charts. :)
2. Minor edits:
"Color can be a useful to indicate emphasis or meaning but should not be the only way information is conveyed."
> either remove the first "a" or add a word after "useful" e.g. "useful way"

**Comment by yatil** [comment]
Agree with Shadi’s point 1.

**Comment by iadawn** [comment]
[EO Meeting 10 Jul](http://www.w3.org/2015/07/10-eo-minutes.html): Resolved to keep good and bad example and question. Some slight changes to the color choice are to be explored, captured in #109
