### ISSUE TITLE
Designing example for Create designs for different viewport sizes

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#75]
http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes

from <https://github.com/w3c/wai-quick-start/issues/53>: "I don't like "Browser display" and "Mobile display". If I'm in a browser on my laptop and I increase the text size a lot, I get the other display. Also, if I have 3 browser windows side-by-side. [medium]"

**Comment by iadawn** [comment]
[Note ignore the referenced commit on labels... it was mis-attributed]

I changed the text:

> Browser display **without zoom** uses multiple columns for primary content

To respond to your concern. I am open to alternative approaches to this though.

**Comment by slhenry** [comment]
Still doesn't really address the issue. How about something like:
* Display in a wide window with small text uses multiple columns...
* Display in a narrow window, such as a mobile phone, or with large text uses single column...

**Comment by iadawn** [comment]
Looks good to me
