### ISSUE TITLE
Designing examples: Ensure form elements include clearly associated labels

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#77]
http://w3c.github.io/wai-quick-start/designing.html#ensure-interactive-elements-are-easy-to-identify

I still want less space between the ends of the labels (e.g., "Your E-mail") and the beginning of the field.

**Comment by iadawn** [comment]
Addressed by 23b3c9869aacda744764772bb782171342daedd9. The labels need to respond to various different sizes, the only way to guarantee close-enough is to right align them.
