### ISSUE TITLE
Is tip for 'Provide a text alternative for images' suitable?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#78]
Tip: [Provide alternative text for images](http://w3c.github.io/wai-quick-start/designing.html#provide-alternative-text-for-images)

Related to: #25

A new tip has been added without complete examples. Is this still considered a suitable tip? Is the wording appropriate? Would the suggested examples help?

**Comment by bakkenb** [comment]
I am in favor of having this tip on the page and including an example of a web clipping with an image that most people think does not need alternative text, but it really does and for good reasons. I will try and think of a good example.

**Comment by sharronrush** [comment]
Yes I like the  concept and the approach but believe it could be seriously tersified.  A suggestion for editor's discretion:

In design comps, provide text descriptions of the purpose or function of graphic elements. Images may be used to convey information, as decorative support, or in various functional ways. Consider what the image is meant to do and provide text that meets that purpose. Decorative images should be presented in CSS or provided with empty alternative text.

**Comment by vmmiller** [comment]
Yes, I like it.  I'd modify the text slightly - with a few steals from dear Sharon above - by removing the first sentence and making some minor edits thereafter:

Images are used in many different ways, such as to convey information, as decorative support, or in various functional ways. Consider what the image is meant to do and provide text which describes that purpose. Decorative images should be presented in CSS or provided with empty alternative text.

**Comment by sharronrush** [comment]
+1 to Vicki's edit, tersification master :)

**Comment by LydiaHarkey** [comment]
As a suggestion for decorative images might be 'Decorative images does not add value to the content therefore the alt text will be a "null value" or "empty alternative text"

**Comment by iadawn** [comment]
Suggestion from @slhenry:

> For each image, provide the purpose of the image in text. This "alt text" will be included in the web code. You do not need to provide alt text for decorative images that don't add information to the page.

**Comment by Egyrs** [comment]
+1 to Vicki's proposal.

**Comment by yatil** [comment]
I still think that this is not in the designer’s domain (apart from content creation which is covered in writing). But I don’t feel to strongly and can live with whatever the group thinks is fine. From the suggestions above, I like Vicki’s better.

**Comment by iadawn** [comment]
[EO Meeting 10 Jul](http://www.w3.org/2015/07/10-eo-minutes.html): Resolved to include a short tip, related to design considerations, succinct and focused

**Comment by AndrewArch** [comment]
+1 to Eric - I'm not so sure this is a design issue vs an authoring issue. Happy with EO resolution and current brief tip.

**Comment by iadawn** [comment]
This topic was discussed in:

* [EO Meeting on 10 July](http://www.w3.org/2015/07/10-eo-minutes.html#alt-text-discuss), and
* [EO Meeting on 17 July](http://www.w3.org/2015/07/17-eo-minutes.html#item06)

**Comment by iadawn** [comment]
Discussed further in [EO Meeting on 7 August](http://www.w3.org/2015/08/07-eo-minutes.html#item03).

Suggestions for examples provided in 1fa3e18.

**Comment by davidberman** [comment]
I am friendly to all the comments above; however in terms of governance and workflow, I think the most importance message to designers about alternative text is they need to push content authors to habituation authoring alternative text when images are selected (so the subject matter expert writes them and they also get adapted to other languages at the same time as other content)... while also acknowledging that sometimes designers are indeed the people selecting some imagery in which case they know know how to author or ask for alternative text, recognize what good alternative text looks like (so they can question poor work). They also need to know how to recognize when an image is decorative, redundant, or trivial... and so a null alt is sufficient or preferred.
