### ISSUE TITLE
Examples & Learn More headings

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#86]
I suggest making them smaller. [low]

**Comment by iadawn** [comment]
Sorry, I am not sure I follow what you are referring to. Could you elaborate?

**Comment by slhenry** [comment]
Use a smaller font size for the Examples & Learn More headings.

**Comment by iadawn** [comment]
Ah right.... shows what I get for looking at things at midnight.

Given this is the same size as in the rest of the WAI site, I am hesitant about changing it.

**Comment by slhenry** [comment]
and less space after

**Comment by slhenry** [comment]
Shawn OK with changing it despite consistency with WAI style -- given the nature of this resource verses others -- e.g., lot less text and really want focus on the h2s

**Comment by slhenry** [comment]
ahhh the proximity fix makes me so very happy ! ! !

**Comment by iadawn** [comment]
Some people are easily pleased 🎉
