### ISSUE TITLE
Learn More links bold or not?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#87]
I wonder if we do not want the prefixes (WCAG Requirements, Background, etc.) bold? In bold, they draw more attention -- maybe more than we want? [low]

**Comment by iadawn** [comment]
I don't knot that they draw that much attention, they seem to balance well with the heading. Then again, I don't know that there is a serious reason to keep them bold.

**Comment by slhenry** [comment]
Kevin tried unbold. prefers bold. Shawn is cool with that.
