### ISSUE TITLE
Examples Formatting

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#89]
I would still *really* like the text size in the examples to be smaller. [medium]

**Comment by iadawn** [comment]
I have two worries:

1. This might then come across as an acceptable font size.
1. All the text that has changed in the examples, not becomes unreadable.

**Comment by iadawn** [comment]
There is quite a bit now to go through with the CSS, SVG scaling, and changing of images. Rather than do all this, I have done one of the examples to show how this might look and uploaded an image of it.

<img width="537" alt="firefoxscreensnapz001" src="https://cloud.githubusercontent.com/assets/2444840/9061867/8d78cf66-3ab6-11e5-9950-d2a350cbfc97.png">

**Comment by slhenry** [comment]
+1 to smaller text for the examples and to also making the labels (e.g., "Inaccessible instruction using color only") smaller -- although that may be less important if all of the example area is on a background (per more comment below). (I'm still [medium] on this, so would accept being overridden by the group's decision otherwise.)

However, I do still think the issue of too-much-going-on is problematic. [high]  E.g., "I also found the page cluttered and so my attention was pulled in many directions while I was looking for its flow. I rendered the page to show just the Heading outline and the structure became much more clear." <https://lists.w3.org/Archives/Public/wai-eo-editors/2015Jul/0043.html>

One thing I think we can do to help is to put *all* of the example -- including the heading and captions -- on a background -- like in the Tutorials, e.g.:<http://www.w3.org/WAI/tutorials/images/informative/#images-used-to-label-other-information>
I'll say I'm [high-medium] on that.

Hummm - it looks like in the Tutorials the example text is smaller, too! ;-) Maybe I'm stronger on that. :-)

Some other ideas are in #30 and #53 - including expand-collapse. I'm not sure if that's in an open GitHub issue elsewhere that I'm not finding?

**Comment by iadawn** [comment]
This is explored further in the [EO wiki](https://www.w3.org/WAI/EO/wiki/Quick_Start_Guides/Styling_of_Examples#Background), and was part of the [EO survey of 21 Aug 2015](https://www.w3.org/2002/09/wbs/35532/EOWG-21Aug2015/results#xq5)

**Comment by sharronrush** [comment]
My problem is the opposite.  I rarely get distracted by images and tend to just skim past them.

**Comment by iadawn** [comment]
Closing with changes to presentation of examples
